### ISSUE TITLE
Support service for EWF chain (and xDai)

### ISSUE THREAD

**Issue by rmeissner** [gnosis/safe-client-gateway#108]
There should be a client gateway to support mobile apps using the EWF chains

### Networks (environment)
- Volta (testnet)
- EWF Mainnet

### To be discussed
- Should we support different chains via different urls rather than different environments

### Dependencies
- https://github.com/gnosis/safe-transaction-service/issues/139

**Comment by Uxio0** [comment]
Services are up and running:

- https://safe-transaction.volta.gnosis.io/
- https://safe-transaction.ewc.gnosis.io/

**Comment by jpalvarezl** [comment]
Spec devops spec sheet updated

**Comment by jpalvarezl** [comment]
xDai was also added to the list of new envs

**Comment by jpalvarezl** [comment]
Production deployment done.
