### ISSUE TITLE
Refactor redis connection

### ISSUE THREAD

**Issue by jpalvarezl** [gnosis/safe-client-gateway#109]
Currently we have exactly 1 redis connection per request (even if unused). This has been done due to issue with the Gnosis provided redis when using multiple connections in a single request.

### ToDos
- [ ] Investigate why this is happening
- [ ] Revert/ refactor changed if possible: https://github.com/gnosis/safe-client-gateway/pull/86

**Comment by Uxio0** [comment]
We don't see any problem
