### ISSUE TITLE
Investigate 500

### ISSUE THREAD

**Issue by jpalvarezl** [gnosis/safe-client-gateway#120]
https://safe-client-rinkeby.staging.gnosisdev.com/v1/safes/0x441E604Ad49602c0B9C0B08D0781eCF96740786a/transactions

```json
{
  "transactionServiceBaseUrl":"https://safe-transaction.staging.gnosisdev.com/api/v1",
  "name":"safe-client-gateway",
  "version":"0.2.0-24-g3e3d8de",
  "buildNumber":"142"
}
```

**Comment by rmeissner** [comment]
This is related to `decodedValue` being highly polymorphic (depends on the method that we are decoding, e.g. `multisend` uses something else than `execTransaction`
