### ISSUE TITLE
Transaction Details invalidation for Multisig types

### ISSUE THREAD

**Issue by jpalvarezl** [gnosis/safe-client-gateway#124]
**Describe the bug**
The URL for fetching transaction details for a Multisig transaction type does not contain the safe address and therefore it is not invalidated by the webhook when there is an update to the safe

**To Reproduce**
- Propose a transaction in a safe with multiple owners
- Issue all the require signatures (do not execute)
- Request the transactions details for the particular transaction and see that the data return is out of date (e.g. status will be `AWAITING_CONFIRMATIONS` instead of `AWAITING_EXECUTION`)

**Expected behavior**
Cache should be invalidated and fresh results should be returned

**Comment by liliya-soroka** [comment]
There is the issue with the rejection transaction state updating from the awaiting confirmation to the cancelled if the rejection transaction details page was opened in awaiting confirmation state
app version 1.12.1 -94 
link on the video https://drive.google.com/file/d/1CYefsF4jLL7qe-bdcmsHNKzpYOwV0xqi/view?usp=sharing
safe 0x1230B3d59858296A31053C1b8562Ecf89A2f888b
nonce 189
Pull to refresh on transaction details doesn't update the state

**Comment by rmeissner** [comment]
As details of transactions are cached with the corresponding safe tx hash they are not invalidated when another transaction with the same is executed. For this we need to adjust our caching to cover this.

Following options:
-> adjust id (this will not work for our fallback where the id is only the safe tx hash)
-> load transactions with same nonce for the safe and invalidate them.

**Comment by jpalvarezl** [comment]
After talking to @rmeissner we decided to make the `safe_tx_hash` part of the transaction Id, which technically has the same implications as option 1 👇 
> -> add safe address to path (this would always work, but requires client changes)

We will fork an additional issue for general cache improvements that will be out of the scope of the apps' public release.
