### ISSUE TITLE
Add liveness and readiness endpoints

### ISSUE THREAD

**Issue by rmeissner** [gnosis/safe-client-gateway#127]
To have good scaling and HA (that’s necessary so traffic can be balanced) we need to provide endpoints to check liveness and readiness. This also allows us to have updates without downtime in a "semiautomated" manner.

### Notes
- https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/
- https://www.openshift.com/blog/liveness-and-readiness-probes
- Concrete implementation needs to be checked
  - Quote by @denisgranha: `you can use any endpoint, it’s better having one with some logic for it as it gives more precise status, but about endpoint it’s enough to check the API it’s up and running`

**Comment by jpalvarezl** [comment]
This might be useful too: https://medium.com/spire-labs/utilizing-kubernetes-liveness-and-readiness-probes-to-automatically-recover-from-failure-2fe0314f2b2e
