### ISSUE TITLE
Collectibles endpoint

### ISSUE THREAD

**Issue by jpalvarezl** [gnosis/safe-client-gateway#132]
**Is your feature request related to a problem? Please describe.**
Currently iOS needs to rely on prefetching `TokenInfo` and caching it for rendering the list of `Collectibles` under `Assets`. The `TokenInfo` is needed for filling out information in the section headers. We can leverage the gateway to return a polymorphic list which aggregates the data, injects sections and creates the entire list.

**Describe the solution you'd like**

The client gateway should return a polymorphic list with 2 item types `Section` and `Collectible` (or a different name).

The data from the endpoints below should be used to generate the list. `collectibles` should be aggregated by address, and the `sections` should be defined using the `tokenInfo`

The transaction service endpoints to use:
`/tokens/` or `/tokens/<address>`
`/safes/<address>/collectibles`

The proposed structures are:
```rust
pub struct Section {
  pub text: String, // this corresponds to `tokenInfo.name`
  pub imageUri: String, // this corresponds to `tokenInfo.logoUri`
}
```

As per the definition of the mobile epic https://github.com/gnosis/safe/issues/287 
 
```rust
pub struct Collectible {
  pub tokenAddress: String,
  pub tokenName: String,
  pub tokenId: String,
  pub name: String,
  pub description: String,
  pub imageUri: String,
}
```

```rust
pub enum CollectiblesListItem{
  Section(Section), Collectible(Collectible)
}
```

The endpoint should return

```rust
pub struct CollectibleList {
  pub items: Vec<CollectiblesListItem>,
}
```

**Comment by jpalvarezl** [comment]
Maybe it is better that the endpoint returns `Page<CollectiblesListItem>` so that if in the future we want to add pagination we don't have make a new version of the endpoint. It doesn't need to implement pagination now though. `next`, `previous` and `count` should be null.

**Comment by rmeissner** [comment]
Maybe we should reopen this for a simple implementation where we only pipe through the response from the transaction service and cache that response (as this endpoint takes a short while to load) cc @jpalvarezl @Uxio0

**Comment by Uxio0** [comment]
Caching would be desired. I also want to optimize this on the core.

**Comment by jpalvarezl** [comment]
No problem. If the spec in the description is agreeable, I could finish it relatively quickly, I would say.

**Comment by rmeissner** [comment]
We should not parse any json from the backend (so no data types on the client gateway for now) and just pipe them through and cache them ;)
