### ISSUE TITLE
Missing outgoing NFT transfers 

### ISSUE THREAD

**Issue by jpalvarezl** [gnosis/safe-client-gateway#144]
Transactions `32` and `33` are displayed in the web app:
- https://safe-team.staging.gnosisdev.com/app/#/safes/0x1C8b9B78e3085866521FE206fa4c1a67F49f153A/transactions

However the gateway does not: 
- https://safe-client-rinkeby.staging.gnosisdev.com/v1/safes/0x1C8b9B78e3085866521FE206fa4c1a67F49f153A/transactions?page_url=limit%3D20%26offset%3D20

**Comment by jpalvarezl** [comment]
At the time of writing this issue, these transactions corresponds to those with nonce `20` and `21`, with respective transaction hashes: 
- nonce `20` and txHash `0x34fae6db48c805403ded59197ff33d564bbd2f9e97654da33234cfec86910290`
- nonce `21` and txHash `0x49bdcc31004a4d3a276ff32c685a901b2371139344bd3a7b461222d9c9fc54e3`

**Comment by rmeissner** [comment]
They do exist in the client gateway the description just uses the next page ... Will close this
