### ISSUE TITLE
Upgrade to Rocket 0.5.0

### ISSUE THREAD

**Issue by rmeissner** [gnosis/safe-client-gateway#15]
Note: For now use `0.5.0-dev`

ToDos:
- [x] Upgrade rocket (https://rocket.rs/master/guide/getting-started/)
- [x] Migrate redis
- [x] Convert all routes to async
- [x] Use async reqwest client
- [x] Create separate env for testing

References:
- Redis support: https://github.com/SergioBenitez/Rocket/issues/1471
- Stable rust support: https://github.com/SergioBenitez/Rocket/issues/19

**Comment by jpalvarezl** [comment]
@rmeissner I don't think we can use `stable` anymore. Not due to rocket but due to `async_closure`

https://github.com/rust-lang/rust/issues/62290

**Comment by rmeissner** [comment]
Hmmm too bad, but not critical for now. We would need nightly in any case in our pipeline for testing.

I would just remove it from the requirement for now, if we see that it is possible in the future we can tackle it at that point.
