### ISSUE TITLE
Include information to check whose signatures are missing in summary item

### ISSUE THREAD

**Issue by jpalvarezl** [gnosis/safe-client-gateway#150]
**Is your feature request related to a problem? Please describe.**
The apps need to render whether the currently selected safe for which there may be a private key associated with, can submit a confirmation for any given MultisigTransaction that they are involved with. For this the app needs to know which `confirmations` have been submitted and if the safe with the associated private key is a `signer` of this safe.

This information is already returned for transaction details, but not for transaction summary items. 

 **Describe the solution you'd like**
The client gateway will return a list of owners that still can sign (`missing_confirmations`) and the client can use this to map the status. The `missing_confirmations` fields is only returned for pending transactions.

After the change the struct would look like this:
```rust
pub struct ExecutionInfo {
    pub nonce: u64, // already exists
    pub confirmations_required: u64, // already exists
    pub confirmations_submitted: u64, // already exists
    // Only available for pending transactions
    pub missing_signers: Option<Vec<String>>,  // new field
}
```

**Describe alternatives you've considered**
Modify the list endpoint to include a query parameter called `owner_address` that will contain the owner address for which the request is trying to fetch the transaction list. the endpoint will look like `/v1/safes/{safe_address}/transactions?owner_address={owner_address}`. 

We would need to introduce a new status variant to `TransactionStatus::MissingOwnerConfirmation` which will set when:
- Transaction is `AwaitingConfirmations`
- the query parameter `owner_address` is one of the addresses in the `SafeInfo.signers` list

**Considerations**
The proposed solution adds a payload overhead to pending transactions (for past transactions, so nonce < current Safe nonce, the `missing_confirmations` would not be rendered, as there are no "missing" confirmations). This overhead would be minimal and the solution would be easy too cache on the client gateway.

The alternative solution would not increase the payload size, but would increase the data we need to cache (as we need to cache different data for different owners). Also might result in more requests from clients.

**Comment by DmitryBespalov** [comment]
Looks good to me, we need signers and confirmations to figure out if user needs to sign a transaction (and display appropriate status), depending on the key stored on the device (client gateway does not store this value, the client does).
