### ISSUE TITLE
Check how to apply style guides

### ISSUE THREAD

**Issue by rmeissner** [gnosis/safe-client-gateway#157]
Currently we are using different IDEs (e.g. IntelliJ and VisualCode) which have a different default formatting. It would be nice to be able to apply a standard so that both autoformat it to the same code.

We might consider adding linting for this too to our build pipeline.

**Comment by Uxio0** [comment]
I think this is a really important issue having multiple people working in the same project, I'm trying to do the same for Python but there are some caveats.

In the case of Rust, there's a style guide https://github.com/rust-dev-tools/fmt-rfcs/blob/master/guide/guide.md and [rustfmt](https://github.com/rust-lang/rustfmt) can be configured to follow that convention. I can take this issue if you want @jpalvarezl @rmeissner
