### ISSUE TITLE
Stop using deprecated endpoint for MultiSig transaction details

### ISSUE THREAD

**Issue by jpalvarezl** [gnosis/safe-client-gateway#165]
We are currently using the `/transactions/` endpoint which was deprecated in favour of `/multisig-transaction` endpoint in the transaction service. 

Initially, it seems like we just need to change the method we use in the gateway and that's it. The object returned has the same structure. We would just need to verify that the filter we are using in the deprecated endpoint is available as well in the new endpoint.

For further details: https://github.com/gnosis/safe-transaction-service/issues/126

**Comment by Uxio0** [comment]
Filters are the same, this is just an endpoint rename 😉
