### ISSUE TITLE
Balances endpoint in non ETH networks returns ETH for native currency balance

### ISSUE THREAD

**Issue by jpalvarezl** [gnosis/safe-client-gateway#179]
## Feature

When the `tokenAddress` is `None` for `mainnet` and `rinkeby` is assumed to be ETH however for xDai and other networks it is not. The gateway sends along `Balance` items the `TokenInfo` for which the `name` and the `symbol` are not nullable and therefore unwrapped as ETH. 

## Solution
We will add the symbol, name and decimals to the env and load them from there when mapping
https://github.com/gnosis/safe-client-gateway/blob/main/src/models/converters/balances.rs#L21-L31

ENV var names:

- `NATIVE_COIN_DECIMALS` : `usize` (Default: `18`) 
- `NATIVE_COIN_SYMBOL` : `String` (Default: `ETH`) 
- `NATIVE_COIN_NAME`: `String` (Default: `Ether`)

**Comment by rmeissner** [comment]
We also show wrong token info for `ETH` should have 18 decimals.

I would go with 3 and 2. So it should be a `Native` and for this token we can define some values via env variables (default should be `Ether`, `ETH` and `18` for `Name`, `Symbol` and `decimals`)

**Comment by rmeissner** [comment]
What are we doing in the transaction list right now?

**Comment by jpalvarezl** [comment]
Transaction summaries that are classified as `Transfers` are any of the variants of this struct: 
```rust
pub enum TransferInfo {
    Erc20(Erc20Transfer),
    Erc721(Erc721Transfer),
    Ether(EtherTransfer),
}
```
Maybe this should be part of a larger effort/refactor/

**Comment by rmeissner** [comment]
Ahhh ... so actually transfers/transactions don't return any token info for eth/native token (I like that) ... hmm but yeah this would be a breaking change to adjust the "type" field from "Ether" to "NativeToken" ... to be consistent maybe we should stick to "Ether" as a synonym everywhere for now and allow the definiton of the information via env variables (so proposal 2)

**Comment by rmeissner** [comment]
alternatively we could render it out as a token with special info ... so no type `Ether` anymore. And we could provide the icon on our service, or the client can have special handling for the "0x0" token (which would be the native token)

**Comment by jpalvarezl** [comment]
right, I think that's also something that @DmitryBespalov thought was acceptable. Reacting to `0x0` in a `tokenAddress` as if it were the `Native` variant. It is potentially a breaking change, but if we add the variant and still keep `Ether` maybe it's not so bad? We could phase it out after some time to let users update.

**Comment by jpalvarezl** [comment]
we could mark the `Ether` variant as `deprecated`

**Comment by rmeissner** [comment]
> we could mark the Ether variant as deprecated

Yes

> It is potentially a breaking change

If we add a token image, then this should be fine. Only place I see this having a potential impact is the details screen, as we say it is a ERC20 transfer but it is a ETHER transfer ... but we trust our backend right now anyways unconditionally.

We could make it a v2

**Comment by DmitryBespalov** [comment]
what about extending this with another type that is 'XDAI' - then it can be handled explicitly on clients?

**Comment by rmeissner** [comment]
that would not scale ... we also have ewc and volta (they use different native tokens on each) ... so at some point we would have a lot of types. The clients need to be aware of the different chain parameter anways.

**Comment by DmitryBespalov** [comment]
Ok, then naming suggestion for the `NetNative` but instead call it `Coin` as it is a chain coin? 😃

**Comment by rmeissner** [comment]
We should load the symbol, name and decimals from env variables:
https://github.com/gnosis/safe-client-gateway/blob/main/src/models/converters/balances.rs#L21-L31

Note: I will update the description with this.

**Comment by jpalvarezl** [comment]
We also need to define what happens to the `TransferInfo::Ether` variant
