### ISSUE TITLE
The transaction list is not loaded for some of the users ("Error(\"invalid type: null, expected u64\)

### ISSUE THREAD

**Issue by liliya-soroka** [gnosis/safe-client-gateway#185]
**Describe the bug**
When the https://safe-client-mainnet.gnosis.io/v1/safes/0xBc79855178842FDBA0c353494895DEEf509E26bB/transactions is called the error is returned : 
![image](https://user-images.githubusercontent.com/338622/98377812-53caad80-2056-11eb-9672-617035487cd4.png)
 
Prod , mainnet
safe = 0xBc79855178842FDBA0c353494895DEEf509E26bB
**Expected behavior**
The tx list should be returned 

**Additional context**

**Comment by liliya-soroka** [comment]
For this safe the ethereum transaction with the tx hash 0x2f920d8b75eff1857266643aedcfcf677b834ca164b6684a23a2c8e4574432ec returns an invalid combination
https://safe-transaction.gnosis.io/api/v1/safes/0xBc79855178842FDBA0c353494895DEEf509E26bB/transfers/

**Comment by jpalvarezl** [comment]
Fixed in #181

 https://safe-client-mainnet.staging.gnosisdev.com/v1/safes/0xBc79855178842FDBA0c353494895DEEf509E26bB/transactions works. Changes need to be deployed.
