### ISSUE TITLE
Properly configure logging

### ISSUE THREAD

**Issue by rmeissner** [gnosis/safe-client-gateway#197]
Things that need to be improved:
- Log errors
  - Make sure errors are notified in Slack
- Disable rocket logging
  - Make sure that normal logging still works

Use Case
- It should be possible to find error logs on kibana with the error code and partial url
- There should be notifications to the team when an error orrurs (e.g. on slack)

**Comment by jpalvarezl** [comment]
I think those noisy logs come from our catchers. I am working on implemeting error logging with a `Fairing`. I will get rid of the catchers as they don't seem to add value.

![Screenshot 2021-02-09 at 13 13 13](https://user-images.githubusercontent.com/11056031/107362142-acd43280-6ad8-11eb-9ded-b15f98bfc7d2.png)
