### ISSUE TITLE
Pagination is missing transactions between pages

### ISSUE THREAD

**Issue by fernandomg** [gnosis/safe-client-gateway#218]
**Describe the bug**
By using the provided `next` URL, there are missing transactions between pages.

**To Reproduce**
1. Call URL `https://safe-client.rinkeby.staging.gnosisdev.com/v1/safes/0x441E604Ad49602c0B9C0B08D0781eCF96740786a/transactions/history?page_url=limit%3D100`
2. Call the `next` URL provided https://safe-client.rinkeby.staging.gnosisdev.com/v1/safes/0x441E604Ad49602c0B9C0B08D0781eCF96740786a/transactions/history?page_url=limit%3D100%26offset%3D100&timezone_offset=0
3. Call the `next` URL provided https://safe-client.rinkeby.staging.gnosisdev.com/v1/safes/0x441E604Ad49602c0B9C0B08D0781eCF96740786a/transactions/history?page_url=limit%3D100%26offset%3D200&timezone_offset=0

The last item for step `2.` is the tx with nonce `249`
The first item from step `3.` is the tx with nonce `247` 

**Expected behavior**
The list returned in step `3.` to start with tx of nonce `248`

**Desktop (please complete the following information):**
all

**Additional context**

**Comment by rmeissner** [comment]
Notes: 
@jpalvarezl  this seems to only happen with page size 100

@fernandomg please avoid adjusting the `page_url` param manually. If you need a minimum amount of txs that should be returned that is larger than 20, we should add a new initial param for that, but please do not manually build or adjust the `page_url` param (only the one used from the backend should be used, and there you should normally always use the full `next` url and not extract params).

**Comment by rmeissner** [comment]
@fernandomg this is expected, as we internally request more elements from our core service (aka transaction service). This one has a max page size of 100. So if we try to request 100 + 2 it will only return 100 and therefore cut off transaction. Therefore coming back to my first statement please do not adjust the `page_url`. If you want to test it with another number you need to choose something below 98 (this should not be released to prod like this). 

Also I recommend to choose an amount as low as possible (e.g. how many tx can fit on a normal screen, testing with my screen the default 20 we currently have would be enough for now).

I will close this issue (as this works as expected if the endpoint is used as expected), if you require a different default page size (other than 20) please open another issue :) (to have a clean issue comment thread ;) )
