### ISSUE TITLE
Special handling of IPFS Safe App URL

### ISSUE THREAD

**Issue by jpalvarezl** [gnosis/safe-client-gateway#224]
## Feature

Check for urls starting with “ipfs.org” :
- Might timeout
- “Ipfs.org” replace with “cloudflare-ipfs.com” (replace only for internal request of the manifest, expose the original URL)

Always try to resolve with the url and the manifest of the safe app

## Additional context

This ticket corresponds to the "optional" feature for #220

**Comment by rmeissner** [comment]
We should probably also introduce a request timeout for the safe app info and/ or cache the error: https://docs.rs/reqwest/0.11.2/reqwest/struct.RequestBuilder.html#method.timeout

Note: this issues cause #327
