### ISSUE TITLE
Transaction History endpoint time offset param

### ISSUE THREAD

**Issue by jpalvarezl** [gnosis/safe-client-gateway#225]
## Enhancement

The `v1/safes/<safe_address>/transactions/history` endpoint returns date labels  foreach day in UTC. This may not reflect the situation of the location where the data is being requested from. The date labels should be added in concordance to the time zone of the requesting client. 

Use the query parameter `timezone_offset` to offset the date label calculation and conditional addition to the list.

**Comment by liliya-soroka** [comment]
Steps to test in mobile app:
1. set up Argentina time zone  (UTC-3)
2. go to the safe 0x1230B3d59858296A31053C1b8562Ecf89A2f888b on staging Rinkeby 
3.  Check txs: 407, 408 and received +0.01 dai
Current result: The date of execution for the txs is  Jan 12 2021

4. Open tx details
Current result: execution date : Jan 13 2021

Expected result: It should be only 4 hours difference between the Berlin time and Argentina time

**Comment by jpalvarezl** [comment]
@rmeissner The transaction details endpoint does not receive the timezone offset as a parameter, so currently we can't offset the dates accordingly.

I see 2 solutions: 
- We modify the details endpoint to expect a `timezone_offset` query parameter just like the `history` and `queued` list and offset the dates in the backend.
- We continue to return the dates in UTC and the clients localize the timestamps depending on their local state. 

Part of this ticket would be to implement the mapper of transaction summaries dependant on the `timezone_offset`. Is this assumption correct?

**Comment by rmeissner** [comment]
We should not offset the dates that are rendered out, this should only affect the grouping when calculating the header position in the history endpoint
