### ISSUE TITLE
MultiSend transactions require the action name in some cases

### ISSUE THREAD

**Issue by jpalvarezl** [gnosis/safe-client-gateway#229]
For `multiSend` transactions, when the action count is `1` the mocks require for the UI to display the method name.

Currently, `Custom` transactions return only the `methodName` (which is `multiSend` in this case) and `actionCount` with the value `1`. There are 2 proposals, in order to avoid having to include the entire `dataDecoded` in the `TransactionInfo::Custom` :

- We agree to always show `action #`, even if it is 1, with no additional `methodName` information.
- We change `actionCount` to `actionInfo` and include a list of the nested method names (I would suggest to only include a single level of nesting to reduce complexity) 

Additional info: [inVision mock](https://projects.invisionapp.com/share/95ZBLISZWNP#/screens/438782607)

![image](https://user-images.githubusercontent.com/11056031/104940885-a14a8b80-59b2-11eb-8880-d2e89a9c477f.png)

**Comment by rmeissner** [comment]
I would go with version 1 or as a third version say we look into the multisend when it is a single action and get it out. But I prefer to not add more special handling so my preference would be to display in the client "1 action" ... actually the web interface should optimize this not use multisend when it is only 1 tx ... would safe some gas.

**Comment by jpalvarezl** [comment]
We will go with uniform behaviour for a single action for the list.
