### ISSUE TITLE
Multisend shown as 0 actions

### ISSUE THREAD

**Issue by tschubotz** [gnosis/safe-client-gateway#236]
**Describe the bug**
Multisend shown as 0 actions

**To Reproduce**
1. Add Safe `0xBc79855178842FDBA0c353494895DEEf509E26bB`
2. Open tx details of tx with nonce 183
-> Multisend with 0 actions and no action decoding.

**Expected behavior**
Multisend with 1 action and function name `swap`

**Screenshots**
![image](https://user-images.githubusercontent.com/1380529/105736858-8db09f00-5f35-11eb-9c3e-47c93529f132.png)
<img src="https://user-images.githubusercontent.com/1380529/105736884-96a17080-5f35-11eb-9d1f-20a3b5e64913.png" width="200" />

**Smartphone (please complete the following information):**
 - Device: Pixel 3a
 - Android Version: 11
 - App Version: 2.8.0-1915

**Environment**
prod mainnet

**Comment by jpalvarezl** [comment]
I've transfered the issue as I found that the problem lies with the type we asign to `value`. In this case it's `755000000000000000000` which causes the error in the deserialiser.

**Comment by rmeissner** [comment]
Shouldn't value be a string?

**Comment by jpalvarezl** [comment]
> https://safe-transaction.gnosis.io/api/v1/safes/0xBc79855178842FDBA0c353494895DEEf509E26bB/multisig-transactions/?nonce=183

It's returned as a number from the transaction service AFAICT. We were also casting it to u64 in the gateway, I will try writing a custom deserialiser to coerce this into a string instead.

**Comment by jpalvarezl** [comment]
if it would be returned as a string from the core services then we would just forward it.

**Comment by rmeissner** [comment]
Yes, we should also change it in the core services (that is why I tagged @Uxio0  ;) )

**Comment by rmeissner** [comment]
Workaround that might be useful for us is

https://github.com/serde-rs/json/issues/434

**Comment by Uxio0** [comment]
It's fixed and will be deployed to staging/dev when github actions is done. I will move it to production next week after confirming that web it's ok. @dasanra , could you check?

**Comment by rmeissner** [comment]
By changing `value` of the multisend tx to a string without adjustments in the client gateway it will break all multisends. @Uxio0

**Comment by Uxio0** [comment]
@rmeissner I've just moved it to `dev` for now, I thought it might break staging. I will wait for your adjustments to move that to staging/prod

**Comment by jpalvarezl** [comment]
I tried using `Number` but for some reason deserialization fails. Could have something to do with the use of `serde:untagged`, but I sunk too much time into it last friday. I will prepare the adjustment to expect a `String` and then we can coordinate the deployment to minimise the time where `multiSend` fails in the gateway. Is that ok?
