### ISSUE TITLE
Transaction domain types

### ISSUE THREAD

**Issue by jpalvarezl** [gnosis/safe-client-gateway#24]
**Is your feature request related to a problem? Please describe.**
The clients currently deserialise the polymorphic response from the `/safe/{address}/all-transactions` into `Multisig`, `Module` and `Ethereum` transactions. Then map each of those types into `Transfer`, `Settings` or `Custom` transaction types. 

**Describe the solution you'd like**
Deserialization is already largely implemented. The domain types (`Transfer`, `Settings` and `Custom`) should be defined according to the needs of the apps.

**Additional context**
For reference, the domain transaction data layouts expected by Android are as follow:

```kotlin
sealed class Transaction {
    abstract val status: TransactionStatus

    // If status is Successful, Failed or Canceled, the confirmations can be null
    abstract val confirmations: Int?

    data class Custom(
        override val status: TransactionStatus,
        override val confirmations: Int?,
        val nonce: BigInteger?,
        val address: Solidity.Address,
        val dataSize: Long,
        val date: String?,
        val value: BigInteger
    ) : Transaction()

    data class SettingsChange(
        override val status: TransactionStatus,
        override val confirmations: Int?,
        val dataDecoded: DataDecodedDto,
        val date: String?,
        val nonce: BigInteger
    ) : Transaction()

    data class Transfer(
        override val status: TransactionStatus,
        override val confirmations: Int?,
        val recipient: Solidity.Address,
        val sender: Solidity.Address,
        val value: BigInteger,
        val date: String?,
        val tokenInfo: ServiceTokenInfo?,
        val nonce: BigInteger?
    ) : Transaction()
}

enum class TransactionStatus() {
    AwaitingConfirmations,
    AwaitingExecution,
    Cancelled,
    Failed,
    Success,
    Pending // Not supported yet as these correspond to the ones issued from the device
}

```

**Comment by rmeissner** [comment]
I would propose the following:
```rust
pub struct Transaction {
    pub id: String,
    pub timestamp: u64,
    pub tx_status: TransactionStatus, 
    pub tx_info: TransactionInfo,
    pub execution_info: Optional<ExecutionInfo>
}

pub enum TransactionStatus {
    AwaitingConfirmations,
    AwaitingExecution,
    Cancelled,
    Failed,
    Success,
    Pending
}

pub enum TransactionInfo {
    Transfer(Transfer),
    SettingsChange(SettingsChange),
    Custom(Custom)
}

pub struct ExecutionInfo {
    pub nonce: u64,
    pub confirmations_required: u64,
    pub confirmations_submitted: u64
}
```

### TBD
- Properties of the TransactionInfo objects
- Should there be a Option<String> for transaction hash
- How to calculate the `id`

**Comment by jpalvarezl** [comment]
Should our `timestamp` already be parsed into `DateTime<Utc>` ? We already have that type used in the deserialization. We'd need to define which field goes into it.

**Comment by rmeissner** [comment]
I prefer a number, as this is easier to handle locally and avoid string parsing on client side ... but depends on what is better for the clients.

**Comment by rmeissner** [comment]
For the id I would propose a format that allows us to distinguish between the different low level tx types (e.g. by using the type as a prefix: `multisig_`, `ethereum_`, `module_`) in combination with information to uniquely identify the information.

**Comment by jpalvarezl** [comment]
I am not sure why `id` is necessary. Is this for the web interface?

**Comment by rmeissner** [comment]
If you want to query the details you need a way to reference what details to load ;)

**Comment by jpalvarezl** [comment]
Then it would make sense to encode what you mentioned here: https://github.com/gnosis/safe-client-gateway/issues/24#issuecomment-664424029 so that we can make a decision of which endpoint we use as there are different ones as I understand it: 
`/safe/{address}/incoming-transfers`, `/safe/{address}/module-transactions`, etc

**Comment by rmeissner** [comment]
I would not add the transaction hash, since it is not required by the mobile interface (web might need it, but in that case we can add it later.)

**Comment by jpalvarezl** [comment]
```rust
pub struct Custom{
    pub to: Address, 
    pub data_size: String,
    pub value: String,
}
```

**Comment by jpalvarezl** [comment]
Do we need `pending` status in gateway? Afaik, this status is only reachable from a device when a transaction is proposed, right?

**Comment by rmeissner** [comment]
A transaction can be failed or cancelled (only ethereum tx are always successful)
