### ISSUE TITLE
Migrate to use github action. Restore caching as it was disabled in the last PR.

### ISSUE THREAD

**Issue by Uxio0** [gnosis/safe-client-gateway#241]
https://github.com/actions-rs/meta
https://levans.fr/rust_travis_cache.html

https://github.com/actions-rs/grcov
https://github.com/actions-rs/example/blob/master/.github/workflows/grcov.yml

https://svartalf.info/posts/2020-04-10-github-action-for-binary-crates-installation/

**Comment by jpalvarezl** [comment]
Done with #248
