### ISSUE TITLE
`SafeInfo` endpoint in the gateway including`AddressInfo`

### ISSUE THREAD

**Issue by Uxio0** [gnosis/safe-client-gateway#242]
## Feature 
`SafeInfo` endpoint in the gateway including`AddressInfo` for:
- `master_copy`
- `owners`
- `default fallback handler`
- `modules`

## Proposal

I suffixed the `struct` names with `Ex` as they are an expanded view of the data supplied by the backend. I am open to suggestions for alternatives.

```rust
pub struct SafeInfoEx {
    pub address: AddressEx, // or String if we don't think it's necessary
    pub nonce: u64,
    pub threshold: u64,
    pub owners: Vec<AddressEx>, // or Vec<String>, if deemed necessary
    pub implementation: AddressEx,
    pub modules: Option<Vec<AddressEx>>,
    pub fallback_handler: Option<AddressEx>,
    pub version: String,
}

pub struct AddressEx {
    pub value: String,
    pub name: Option<String>,
    pub logo_url: Option<String>,
}

```

All field names will be `camelCased` in the `json` response.
Network request for `AddressInfo` will not be issued for `address` and `owners` as usually this will not be a hit and it would be overridden by local data of the apps, however in the future we may want this.

**Comment by rmeissner** [comment]
I would propose not to add address info for `owners` as it is unlikely to return any results and would therefore only add a request overhead. 

As we need to create a new endpoint for this in any case, it might still make sense to use the format that allow us to add this for `owners` in the future (basically the same that will then be used for `modules`)

**Comment by jpalvarezl** [comment]
Just to make things clear: For the the `creator` and `factory` fields, I would need to additionally fetch the `Creation` tx for the safe.
