### ISSUE TITLE
Adding CancelTransaction variant for transaction related endpoints

### ISSUE THREAD

**Issue by jpalvarezl** [gnosis/safe-client-gateway#255]
## Feature

Currently the web app classifies cancelation transactions on its own. It would be good to push this logic to the gateway, so clients can benefit of not having to implemente this themselves, while at the same time having a more uniform data representation across apps.

## Proposal 1

```rust
pub enum TransactionInfo {
    Transfer(Transfer),
    SettingsChange(SettingsChange),
    Custom(Custom),
    Creation(Creation),
    Cancellation(Cancellation), // new
    Unknown,
}

pub struct Cancellation {
  // TBD: web does not require fields for the UI but the clients might
}
```

## Proposal 2

```rust
pub struct Custom {
    pub to: String,
    pub data_size: String,
    pub value: String,
    pub method_name: Option<String>,
    pub action_count: Option<usize>,
    pub to_info: Option<AddressInfo>,
    pub is_cancellation: bool, // new
}
```
## Endpoints

Any endpoint returning transactions. That would be:
- `v1/safes/<address>/transactions`
- `v1/safes/<address>/transactions/history`
- `v1/safes/<address>/transactions/queued`

## Resources

Currently the web app identifies cancellation transactions using the following criteria:
https://github.com/gnosis/safe-react/blob/d17da5489b595385544fea426fcabadb40e7a168/src/logic/safe/store/actions/transactions/utils/transactionHelpers.ts#L52-L86

In `Suggested Fix` section the classification heuristic is defined in steps: https://github.com/gnosis/safe-react/issues/1800

Using fields from the transactions served by the gw:

```js
export const isCancelTransaction = ({ txInfo, safeAddress }: { txInfo: Custom; safeAddress: string }): boolean =>
  sameAddress(txInfo.to, safeAddress) &&
  sameString(txInfo.dataSize, '0') &&
  sameString(txInfo.value, '0') &&
  txInfo.methodName === null
```

**Comment by rmeissner** [comment]
why do we use a new variant? this will break all existing clients. Why not just use a flag for now?

**Comment by jpalvarezl** [comment]
I will bring this issue up in the refinement meeting so everyone can have a say an estimate the impact of this. We don't need to proceed with the `Proposal` but it's good to at least have documented how to classify the TX and then we can decide how we serve it (either flag or new variant depending on what breaks less stuff :) )

**Comment by rmeissner** [comment]
So if this is required by the web team for the initial version then we should implement this asap, e.g. this week (we need a comment from web and product how important this is). The implementation effort is minimal, only open question is about breaking the existing clients.

Notes to proposal 2:
I would make `is_cancellation` a `bool` (so not an Option)

**Comment by rmeissner** [comment]
We could go with proposal 1 behind a new endpoint and just add a flag to our converter if we should render Cancel or Custom (e.g. here https://github.com/gnosis/safe-client-gateway/blob/main/src/models/converters/transactions/mod.rs#L67) then when we see that the v1 endpoint is not used anymore we remove the old logic (v1 can then either forward to v2 or we remove it completely and force clients to update)
