### ISSUE TITLE
Add "Already rejected" flag to transaction details

### ISSUE THREAD

**Issue by MouazAlzahabi** [gnosis/safe-client-gateway#258]
## Feature

**Is your feature request related to a problem? Please describe.**
In the proper rejection feature, we need to know that the transaction was already rejected in order to disable rejection feature. otherwise user will be able to submit multiple cancelation for one tx.

**Describe the solution you'd like**
- First option: Add "isRejected" flag to transaction details response 
- Second option: Return "rejections" as list of signatures same as "confirmations", this will be helpful later if we wanted to show who rejected the tx in timeline box. 

**Edit by @jpalvarezl **

## Proposal

Modify transaction details to contain the list of rejections in the `MultisigExecutionDetails` struct, like so:

```rust
pub struct MultisigExecutionDetails {
    pub submitted_at: i64,
    pub nonce: u64,
    // .... 
   pub confirmations: Vec<MultisigConfirmation>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub rejectors: Option<Vec<String>>, //new
   //...
}
```

**Comment by rmeissner** [comment]
I would propose to return an array of addresses that have confirmed the cancelation transaction, as this is more inline with how we handle it with "Awaiting *your* confirmation". Else we would have to send along the owner address (else we would not know who they rejected), which would make our caching harder to optimize.

**Comment by DmitryBespalov** [comment]
@jpalvarezl can you please put a short JSON example? Do I understand right that this field will be part of the `detailedExecutionInfo`?

```json
{ // transaction details response
  "txInfo": ...,
  "detailedExecutionInfo": {
    "type": "MULTISIG",
    "signers": [ ... ], // checksummed addresses of signers
    "rejections": [ ... ] // checksummed addresses of rejectors. Optional (may be not present at all),
    ...
  }
}

```
