### ISSUE TITLE
V2 transaciton endpoints feature request compilation

### ISSUE THREAD

**Issue by jpalvarezl** [gnosis/safe-client-gateway#260]
TODO's:

- [ ] correct serve camelCasing for all variants of `SettingsInfo` (verify other endpoints too)
- [ ] Replace any address with an `AddressInfo` object
- [ ] remove `is_cancellation` flag from `Custom` transactions and create a new variant of `TransactionInfo::Cancellation`

**Comment by rmeissner** [comment]
Consistent use of `Uri` and `Url` (currently we mix them)
