### ISSUE TITLE
Queue and history endpoints return errors after Safe creation for some time.

### ISSUE THREAD

**Issue by tschubotz** [gnosis/safe-client-gateway#269]
_(I guess this is somewhere in between bug and expected behavior.)_

**Describe the bug**

**To Reproduce**

1. Create a new Safe via the web interface. e.g. `0x8348D74d77CC9A10E0bef9a693cc957EC1A8A3dD`
2. https://safe-client.rinkeby.staging.gnosisdev.com/v1/safes/0x8348D74d77CC9A10E0bef9a693cc957EC1A8A3dD/transactions/history/ and https://safe-client.rinkeby.staging.gnosisdev.com/v1/safes/0x8348D74d77CC9A10E0bef9a693cc957EC1A8A3dD/transactions/queue return an error.
3. https://safe-transaction.rinkeby.staging.gnosisdev.com/api/v1/safes/0x8348D74d77CC9A10E0bef9a693cc957EC1A8A3dD loads right away also https://safe-transaction.rinkeby.staging.gnosisdev.com/api/v1/safes/0x8348D74d77CC9A10E0bef9a693cc957EC1A8A3dD/creation/
4. After some time (~15min), the queue return a 404 (expected) and the history returns the creation tx (expected) 

**Expected behavior**

History and queue return the expected results right away.

**Additional context**

- Richard says this might be a caching thing due to /creation on the tx service taking a bit (~several seconds) initially. 
- Linking #246 since it could be related.
- Also linking the client issue where this was detected: gnosis/safe-react#1906

**Comment by jpalvarezl** [comment]
This would be solved by this, right ? https://github.com/gnosis/safe-transaction-service/issues/220 @rmeissner

**Comment by rmeissner** [comment]
Yes I think so, let check this on rinkeby and then we can close it :)

**Comment by rmeissner** [comment]
I checked this on rinkeby and seems to work as expected now

**Comment by tschubotz** [comment]
fyi @liliya-soroka @francovenica in case you'd like to test
