### ISSUE TITLE
Ethereum transactions without `to` crash service

### ISSUE THREAD

**Issue by rmeissner** [gnosis/safe-client-gateway#271]
Currently our `EthereumTransaction` object requires the `to` field. As deployment transactions on Ethereum don't have a `to` this can be `null` and in this cases the service will crash.

Question: Should we remove ununsed fields from the reponse to avoid that these unused fields impact our stability/ performance

**Comment by jpalvarezl** [comment]
I would opt for simply removing this field. If eventually we do need it for something, we add it back in.
