### ISSUE TITLE
`origin` can be used to trigger a call from the client gateway to anywhere

### ISSUE THREAD

**Issue by rmeissner** [gnosis/safe-client-gateway#275]
- Check if this is a security issue
  - Could you create a loop where the origin points to the safe transaction itself and therefore results in the interface calling itself? 
- In some cases this caused a blocking call (as we did not have a connection timeout) which at some point blocked the whole service. 
  - Switch to non blocking version of `reqwest`  

Solutions:
- Disallow `localhost` as source
- Disallow static IPs as source (aka require a dns entry)
- Only allow http protcols

**Comment by jpalvarezl** [comment]
For non blocking `reqwest` migration, it could be worth checking out this: https://github.com/SergioBenitez/Rocket/issues/1065

**Comment by rmeissner** [comment]
We do not need to wait for this, as according to the rocket docs they already support async io (see https://rocket.rs/master/guide/overview/#futures-and-async). This still would be a major change that would affect the whole app.
