### ISSUE TITLE
Evaluate and increase timeout for requests

### ISSUE THREAD

**Issue by jpalvarezl** [gnosis/safe-client-gateway#278]
- [x] Compile cache durations and check the current state. 

**edit**
`SAFE_APP_MANIFEST_CACHE_DURATION` is not defined in the spec doc of the gateway, it is therefore using the default value.

- Defaults: (as per the spec doc and the code defaults)
```
INFO_CACHE_DURATION = 60 * 15 (15 minutes)
EXCHANGE_API_CACHE_DURATION = 60 * 60 * 12 (12 hours)
REQUEST_CACHE_DURATION" = 60 * 15 (15 minutes)
ABOUT_CACHE_DURATION =  REQUEST_CACHE_DURATION
SAFE_APP_MANIFEST_CACHE_DURATION =  60 * 60 * 24 * 7 (1 week)
```

- `Staging` is using the default values written about ☝️ 

- `Production` is using the default for `EXCHANGE_API_CACHE_DURATION` and `SAFE_APP_MANIFEST_CACHE_DURATION`. The rest of the values are defined as following: (as per the spec doc)
 
```
INFO_CACHE_DURATION =  =  60 * 60 * 24 * 7 (1 week)
REQUEST_CACHE_DURATION" =  60 * 60 * 24 * 7 (1 week)
ABOUT_CACHE_DURATION =  60 * 10 (10 minutes) 
```

- [x] Draft a proposal for new timeouts

Get rid of `SAFE_APP_MANIFEST_CACHE_DURATION` and use `INFO_CACHE_DURATION` in its place. Proposed values:

```
EXCHANGE_API_CACHE_DURATION = 60 * 60 * 12 (12 hours)
REQUEST_CACHE_DURATION" = 60 * 60 * 24 * 7 (1 week)
INFO_CACHE_DURATION = 60 * 60 * 24 * 7 (1 week)
ABOUT_CACHE_DURATION =  60 * 10
REQS_ERROR_CACHE_DURATION = 60 (1 minute)
INFO_ERROR_CACHE_DURATION = 60 * 60 * 24 (1 day) # it used to be 10000 in the TokenInfo PR, maybe we should reduce to ~ 3 hours to match?
```

- [ ] Notify devOps requesting the changes

**Comment by jpalvarezl** [comment]
@rmeissner I think this contains the final proposal so far. Just would need to think about the `INFO_ERROR_CACHE_DURATION` and whether 24 hours is fine. You had it as 10000 seconds (~ 3 hours) in the TokenInfo PR. I would ask devOps to update this values in the next production deployment. I would update the spec doc. 

Do we want the same values for staging?

**Comment by rmeissner** [comment]
What is the advantage of `Get rid of SAFE_APP_MANIFEST_CACHE_DURATION and use INFO_CACHE_DURATION in its place.`?

On another note, for the token info we currently use `INFO_CACHE_DURATION`, that would mean that if new tokens show up in the meantime they will not be visible via the token info.

**Comment by jpalvarezl** [comment]
> What is the advantage of Get rid of SAFE_APP_MANIFEST_CACHE_DURATION and use INFO_CACHE_DURATION in its place.?

Just separating things depending one where we are fetching them from. the `SafeApp` stuff gets fetche from the `InfoProvider` that's why I associated that timeout with it.

That makes sense, then we should isolate the `TokenInfo` case for now? Since we have webhooks for everything else. We can keep `REQUEST_CACHE_DURATION` add `AGGREGATED_TOKEN_CACHE` to be 1 day. We could continue to use `INFO_CACHE_DURATION` for this case, we could just bring it down to 1h

**Comment by jpalvarezl** [comment]
> What is the advantage of Get rid of SAFE_APP_MANIFEST_CACHE_DURATION and use INFO_CACHE_DURATION in its place.?

Also trying to kep the env vars to the minimum required, if we get too many it's gonna be easy to get confused.

**Comment by rmeissner** [comment]
>  if we get too many it's gonna be easy to get confused.
The thing is that most of them have different requirements. And maybe we should list all the different information and what timeout we use. Information we fetch: Safe info, Token info, Contract info, Safe app info. Does it make sense that we put them all under the same timeout? Question here would be when do we expect them to change? And do we get notified about the change? You know what I mean?

**Comment by jpalvarezl** [comment]
Yeah, I think I understand now. I will compile a list of what I am aware of and leave here as a comment :) I will phrase this from the perspective of the objects we return, rather than the timeouts themselves.

**Comment by jpalvarezl** [comment]
- InfoProvider related:
    - `load_token_info` calls check_token_cache` which calls `populate_token_cache`. This creates a marker in the cache `dip_tcl` with timeout `INFO_CACHE_DURATION` or `INFO_ERROR_CACHE_DURATION` if it's an error.
    - If `populate_token_cache` is successful, it creates individual entries for each cache with time out `INFO_CACHE_DURATION`
    - `fetch_exchange` fetches fiat conversion rates and caches them with a timeout of `EXCHANGE_API_CACHE_DURATION` and for error `INFO_CACHE_DURATION` **NOTE: This error timeout seems is misused**
    - `load_safe_info` has a timeout of `INFO_CACHE_DURATION` and for error `INFO_CACHE_DURATION`
    - Both `safe_app_info` and `address_info` use timeout `SAFE_APP_MANIFEST_CACHE` and for error `INFO_ERROR_CACHE_DURATION`
- Matched route requests:
    - Request to core services: `timeout = REQUEST_CACHE_DURATION` and `error timeout = REQS_ERROR_CACHE_DURATION`
    - Mapped responses: `timeout = REQUEST_CACHE_DURATION` and we don’t cache errors originating from the gw
- `Context::request_cached` has a `timeout` parameter which is `REQUEST_CACHE_DURATION` for core services requests. Internally it adjusts the timeout to  `REQS_ERROR_CACHE_DURATION` for `4xx`. Core services`5xx`s are not cached.

**Comment by rmeissner** [comment]
So we also have contract info stuff, right? Lets do a quick call on friday or monday to figure this out finally. You collected a lot of information, but I would like to to a 30 min call to sort it out. Would that work?

**Comment by jpalvarezl** [comment]
yeah, for sure. Let's have a call on friday 👍

**Comment by jpalvarezl** [comment]
indefinitely = 1 week
- `SafeInfo` can be cached indefinitely (this will be updated through webhooks) and error should be 1 minute
- `AddressInfo` and `SafeAppInfo` this should be cached indefinitely and error 1 day
- `TokenInfo` should be cached for 1 day and errors are cached 1 minute
- `fetch_exchange` cache unchanged (12 hours) error timeout is 1 minute
- Outter endpoint matches cache indefinitely, error timeout 1 minute

Proposed env variables:
Split INFO_CACHE_TIMEOUT -> ~~SAFE_APP_MANIFEST_DURATION~~, TOKEN_INFO_DURATION, SAFE_INFO_DURATION, ADDRESS_INFO_DURATION

Add LONG_ERROR_DURATION, SHORT_ERROR_DURATION (1 day and 1 minute, respectively)

Notify DevOps we will remove `INFO_CACHE_DURATION`
