### ISSUE TITLE
Noisy error alerts for services

### ISSUE THREAD

**Issue by jpalvarezl** [gnosis/safe-client-gateway#281]
Relates to https://github.com/gnosis/safe-client-gateway/issues/269

Issue #269 triggers a 500 in the gateway even though the core services report it as a 404. 

We should:
- Pipe 404s (maybe all 4xx) through to the clients
- Adjust our custom responder to not log 4xx

**Comment by rmeissner** [comment]
We should adjust https://github.com/gnosis/safe-client-gateway/blob/HEAD/src/utils/errors.rs#L121 to not format the error but instead use something similar to https://github.com/gnosis/safe-client-gateway/blob/HEAD/src/utils/errors.rs#L42
