### ISSUE TITLE
Rocket error crashing pod

### ISSUE THREAD

**Issue by jpalvarezl** [gnosis/safe-client-gateway#284]
`[2021-02-25T13:17:19Z ERROR rocket::rocket] Failed to write response: Os { code: 32, kind: BrokenPipe, message: "Broken pipe" }`

Error causes the pod to crash. The issue has been documented  here:
- https://github.com/SergioBenitez/Rocket/issues/286 
- https://github.com/SergioBenitez/Rocket/issues/17

Seems like the cause can be the size of the `Content-Length` or spikes in requests/second.

**Comment by jpalvarezl** [comment]
I have been reading a bit more about this. The issue could be associated with `write!` as some links might suggest:
- https://github.com/openethereum/parity-ethereum/issues/10342 (they have the same issue)
- https://github.com/denoland/deno_std/issues/659

As far as I get it there is a stream into which we are trying to write that somehow becomes inaccessible from our end? Could be the changes we did in the responder to handle errors better that's somehow tripping up with deserialising errors or something like that?

Solutions? Not sure if we call it solutions, maybe just workarounds:
- https://github.com/denoland/deno_std/issues/659
- http://yukimemi.github.io/post/2018-01-07_fix-broken-pipe-in-rust/ (in Japanese)

**Comment by mtb-pro** [comment]
I had this problem before
your rpc port is under attack 
your rpc port should be restricted to a specific IP
