### ISSUE TITLE
[Research] Aggregate performance logs

### ISSUE THREAD

**Issue by rmeissner** [gnosis/safe-client-gateway#291]
Currently each request generates a log message for performance monitoring purposes.

We should batch these logs somehow in redis and only trigger a send every x requests or x minutes

**Comment by jpalvarezl** [comment]
Thinking about this a bit more closely, I think this implementation is heavily dependent on being able to use different databases in redis.

The reason is what we log:

```rust
log::info!(
            "MT::{}::{}::{}::{}::{}::{}",
            method,
            route,
            delta,
            status_code,
            request.uri().to_string(), // full path with query params
            chain_id
        );
```

A webhook invalidation would also hit our logs containing safe addresses.
