### ISSUE TITLE
NFT staying in the Collection least for too long after a transfer

### ISSUE THREAD

**Issue by francovenica** [gnosis/safe-client-gateway#324]
**Describe the bug**
When an NFT is transferred from a safe to another, the receiving safe shows it pretty quickly, but it still keeps showing in the safe it was sent from for a long time

**To Reproduce**
Prerequisite: In rinkeby dev environment, have 2 safes. One with at least 1 NFT

Send a NFT from one safe to another
Check the safe's collectibles list that receives it until it shows
Check the safe's collectibles list where it was sent from

**Current behavior**
The NFT shows in both safes at the same time. It takes too long (around 30 mins or more) for the NFT to disappear from the safe it was sent from

**Expected behavior**
The NFT shows in the safe's collectibles list it was sent to and it doesn't show in the safe's collectibles list it was sent from

**Comment by rmeissner** [comment]
Assumption from my side: I assume that invalidate the asset list when the outgoing tx is executed but the core services have not yet indexed the event and therefore have not update the asset list. For the receiving account we get a hook once the nft is received.

@Uxio0 should/ could we get a hook when an asset is transferred out?

**Comment by Uxio0** [comment]
> @Uxio0 should/ could we get a hook when an asset is transferred out?

Sure, then for every `INCOMING_TOKEN` I would also emit an `OUTGOING_TOKEN`: https://github.com/gnosis/safe-transaction-service/issues/238

**Comment by Uxio0** [comment]
@rmeissner Do you think `OUTGOING_ETHER` is also needed? I can implement both just in case

**Comment by Uxio0** [comment]
> Edit: Also ether can only be transfered out with a multisig transaction, as it is not possible to "approve" Ether. So I don't think it has much value.

I agree. Either way as it was easy I just implemented it, in case we need it for a new notification or you don't want to parse the outgoing transaction

**Comment by Uxio0** [comment]
New webhooks are already available on staging

**Comment by jpalvarezl** [comment]
Verified on staging
