### ISSUE TITLE
Add request timeouts to core service requests

### ISSUE THREAD

**Issue by jpalvarezl** [gnosis/safe-client-gateway#340]
There is already a `Connection` timeout for the `reqwest::client` and specifically for IPFS requests reads, as well.

Should we set the timeout [here](https://github.com/gnosis/safe-client-gateway/blob/0393127d68f59daf19d51fe2d4aa0f421f4dd516/src/main.rs#L39) not only for `Connection`? 

No, different endpoints require different timeouts.

## Proposal

- Transaction related endpoints: 30 [s]
- Safe Info: 10 [s]
- Token Info: 5 [s]
- Safe App Info: no change
- Default: 5[s] (for balances, collectibles, contract info, etc)

**Comment by rmeissner** [comment]
Timeout are very use case specific, and we should set them based on that. The connection timeout can be generalized as it indicates if there is an initial response by the service we try to connect to (e.g. is it even available). But loading data from a service depends very much on that service. Also we might give more time to our service then we do with external services.
