### ISSUE TITLE
Pay for the exchange rates api

### ISSUE THREAD

**Issue by Uxio0** [gnosis/safe-client-gateway#345]
- Would be $100 per year
- We could perform more requests (currently 250/m are free, we request 2 a day per service ... so we would need to lower this, new limit would be 10k)
- More recent exchange rate (free is daily, basic is hourly, so we could also try to fetch more often than twice a day)
- https support

**Comment by jpalvarezl** [comment]
https://exchangeratesapi.io/pricing/ will allow us to have hourly updated prices. Should we reduce the cache duration of this information to 1 hour? 

We will continue the free usage with staging. Meaning that `https` will only be able for production. We are ok with this?

**Comment by jpalvarezl** [comment]
This requires only a change in the env var `EXCHANGE_API_BASE_URL` to `https://api.exchangeratesapi.io/latest`. I left a comment in the next milestone to remind of that: https://github.com/gnosis/safe-client-gateway/milestone/17
