### ISSUE TITLE
Adjust `domainSeparator` for calculating the `safeTxHash` for cancellation TXs

### ISSUE THREAD

**Issue by jpalvarezl** [gnosis/safe-client-gateway#348]
Version 1.3.0 of the safe contracts introduce a new way of calculating the `domainSeparator`.

Currently, this is simply hardcoded in the GW which will no longer be valid for transactions issued from +1.3.0

## Proposal

1. Fetch `SafeInfo` and verify `version`
2. Fallback to old `domainSeparator` if version < 1.3.0
3. Calculate the `domainSeparator` according to: https://github.com/gnosis/safe-contracts/blob/53122d14af0a3f6aa30c5fcd3861573d44c9d7b9/contracts/GnosisSafe.sol#L360

## Dependencies

How do we determine the `chainId` ?
Env variable.

**Comment by Uxio0** [comment]
> How do we determine the chainId ?
I can return it on `SafeInfo`

**Comment by jpalvarezl** [comment]
That would be super convenient actually :)

**Comment by Uxio0** [comment]
I think maybe is better to return it somewhere else, as it will be common for the whole service and it doesn't make a lot of sense in the SafeInfo endpoint. Maybe `api/v1/about/`?

**Comment by jpalvarezl** [comment]
the about endpoint would also make sense. Then we would have 2 requests from the GW which I guess is not that terrible, but I was thinking that we could try to somehow derive it from the URL we use as base for requests to TX service. That doesn't scale though :thinking: everything would be hard coded, I think.

**Comment by jpalvarezl** [comment]
which endpoint do you return the information about the last indexed block? Would it make sense to return the chain Id there?

**Comment by Uxio0** [comment]
> the about endpoint would also make sense. Then we would have 2 requests from the GW which I guess is not that terrible, but I was thinking that we could try to somehow derive it from the URL we use as base for requests to TX service. That doesn't scale though 🤔 everything would be hard coded, I think.

Why not caching the `chainId` when the service starts? It should never change

**Comment by Uxio0** [comment]
> which endpoint do you return the information about the last indexed block? Would it make sense to return the chain Id there?

`v1/about/master-copies/`. I don't think it makes sense to expose that info there. I would do `v1/about/ethereum/` exposing current block, node version and some other stuff that could be useful

**Comment by jpalvarezl** [comment]
> Why not caching the chainId when the service starts? It should never change

This could even be extracted to an env var :thinking:

**Comment by Uxio0** [comment]
> > Why not caching the chainId when the service starts? It should never change
> 
> This could even be extracted to an env var 🤔

That's right, less complex
