### ISSUE TITLE
Known Addresses v4

### ISSUE THREAD

**Issue by jpalvarezl** [gnosis/safe-client-gateway#353]
## Feature

- Adding a new endpoint `/v2/transactions/<transaction_id>`
- Decoupling `serialiser` and `deserialiser` of `DataDecoded` to be able to serve the new data structure
- Replace `ModuleExecutionDetails::address : String` with `ModuleExecutionDetails::AddressEx` 

## Context

Currently, for transactions details, we return `DataDecoded` untouched from the backend services. The structure is as follows:
(for readability reasons, I've removed the macros)
 
```rust
pub struct TransactionDetails {
    pub executed_at: Option<i64>,
    pub tx_status: TransactionStatus,
    pub tx_info: TransactionInfo,
    pub tx_data: Option<TransactionData>,
    pub detailed_execution_info: Option<DetailedExecutionInfo>,
    pub tx_hash: Option<String>,
    pub safe_app_info: Option<SafeAppInfo>,
}

pub struct TransactionData {
    pub hex_data: Option<String>,
    pub data_decoded: Option<DataDecoded>,
    pub to: String,
    pub value: Option<String>,
    pub operation: Operation,
}

pub struct DataDecoded {
    pub method: String,
    pub parameters: Option<Vec<Parameter>>,
}

pub struct Parameter {
    pub name: String,
    pub param_type: String,
    pub value: ParamValue,
    pub value_decoded: Option<ValueDecodedType>,
}
```

## Proposal

The `crate::models::commons` module would split up into `crate::models::backend::data_decoded` module (containing the current structs for `DataDecoded`) and `crate::models::services::data_decoded` containing the structs with the changes proposed here:

```rust

// only for serialization
pub struct DataDecoded {
    pub method: String,
    pub id: Option<String>,
    pub parameters: Option<Vec<Parameter>>,
}


pub struct Parameter {
    pub name: String,
    pub abi_type String,
    pub hex_value: Option<String>
    pub value: ParamValue,
}

pub enum ParamValue {
    SingleValue(String),
    ArrayValue(Vec<ParamValue>),
    Data(String),
    Address(AddressEx),
    MultiSendTx(Vec<InternalTransaction>),
    Unknown,
}

pub struct InternalTransaction {
    pub operation: Operation,
    pub to: String,
    pub value: Option<String>,
    pub data: Option<String>,
    pub data_decoded: Option<DataDecoded>,
}
```

This would introduce a new version of the transaction details endpoint as well as `crate/models/services` structs to decouple our models from those of the backend.

Additionally, `ModuleExecutionDetails::address: String` can be easily modified to be `AddressEx` if there is a new endpoint version released. 

`DataDecoded::id: Option<String>` will always be null for now. This field is a placeholder, for when we are able to allow clients to request a specific level of nesting of decoded data.

## References

https://docs.google.com/document/d/1JADxSxlA3JdFcR31CuGuGe8C_tBPgPKjXXoF_OUUlrc/edit#

![image](https://user-images.githubusercontent.com/11056031/116232407-5fbc4000-a75a-11eb-857a-152410516d1e.png)

**Comment by sche** [comment]
Thank you for the detailed description.
I have a question. According to diagram param `MultiSendTx(Vec<InternalTransaction>)`, should be `MultiSendTx(InternalTransaction),`. Does it make sense to express multiple internal transactions for multi-send as ArrayValue(MultiSendTx(InternalTransaction)), or `MultiSendTx(Vec<InternalTransaction>)` is more explicit?

**Comment by Uxio0** [comment]
> MultiSendTx(Vec<InternalTransaction>)

IMHO `MultiSendTx(Vec<InternalTransaction>)` is more explicit

**Comment by Uxio0** [comment]
> Thank you for the detailed description.
> I have a question. According to diagram param `MultiSendTx(Vec<InternalTransaction>)`, should be `MultiSendTx(InternalTransaction),`. Does it make sense to express multiple internal transactions for multi-send as ArrayValue(MultiSendTx(InternalTransaction)), or `MultiSendTx(Vec<InternalTransaction>)` is more explicit?

IMHO `MultiSendTx(Vec<InternalTransaction>)` is more explicit

**Comment by jpalvarezl** [comment]
The only way to have `InternalTransactions` is through either `execTransactions` and `multiSend` calls, as far as I know. 

If I understood you correctly, `ArrayValue(MultiSendTx(InternalTransaction))` , according to what I see, would make the relationship `MultiSendTx` -> `InternalTransaction` as `1:1` always. Additionally, what you would be expressing with that typing, would be multiple multiSend calls with single `InternalTransactions` rather than a `multiSend` with many `InternalTransactions`
