### ISSUE TITLE
Update `.env.sample`

### ISSUE THREAD

**Issue by jpalvarezl** [gnosis/safe-client-gateway#386]
The `.env.sample` file is outdated. 

We need to introduce the following changes:

(rename) `ROCKET_LOG` -> `ROCKET_LOG_LEVEL`
(remove)  `ROCKET_DATABASES={service_cache={url="redis://127.0.0.1:6379"}}`
(add) `REDIS_URL="redis://127.0.0.1:6379"` 
(add) `FEATURE_FLAG_NESTED_DECODING=true`

**Comment by rmeissner** [comment]
Env var declarations should not have spaces around the `=` ;)
