### ISSUE TITLE
Decode module transactions

### ISSUE THREAD

**Issue by rmeissner** [gnosis/safe-client-gateway#387]
Currently module transactions are always decoded as `Custom` (see https://github.com/gnosis/safe-client-gateway/blob/main/src/models/converters/transactions/mod.rs#L253)

We should apply similar decoding as for a multisig transaction (see https://github.com/gnosis/safe-client-gateway/blob/main/src/models/converters/transactions/mod.rs#L68)

#### Notes
- [ ] Check with the clients that this is no issue (especially check how this affects web)
  - Maybe add a feature flag for it or a new endpoint
- [x] ~Check if we should make [`ExecutionInfo`](https://github.com/gnosis/safe-client-gateway/blob/main/src/models/service/transactions/summary.rs#L13) polymorphic to also return module information (would be a new endpoint if this breaks the clients) -> might be a separate issue.~ (Not Now)

**Comment by jpalvarezl** [comment]
As I understand this issue, we need to attempt mapping of `ModuleTransactions` as we do `MultisigTransaction` meaning that the only part that changes is the `transaction_info`. This will affect both the list and details endpoint too.

I personally don't see any risks for the clients, as we are returning structures they are expecting. The notion of `Multisig` or `Module` is hidden to them. If it's only the gw they are consuming.

Regarding `ExecutionInfo`, you mean to add the `AddressInfo` ? Is this necessary in the list endpoint? As this could be part of the `ModuleExecutionDetails` in the details endpoint. 

Wouldn't it be simpler to add a flag for `Custom` transaction info that tells the clients that this originates from a module?
