### ISSUE TITLE
Implement detail endpoint

### ISSUE THREAD

**Issue by rmeissner** [gnosis/safe-client-gateway#39]
TBD

**Comment by rmeissner** [comment]
I would propose a datastructure that is quite generic and is close to the design.

The following section would be in the data (sections for optional data should be hidden in the ui if not present):
- status (see #24)
- transaction info (see #24)
- data (optional)
  - bytes
  - decoded (optional)
- executedAt (optional)
- submittedAt (optional)
- detailed execution info (optional)
  - safeTxHash
  - nonce
  - operation
  - confirmations (list of addresses + date of confirmation submission)
  - missing confirmations (list of addresses)
- txHash (optional)

### Notes
- I would always add the `data` section if available, as it would allows us to fallback to a custom tx in the clients in case an unknown transaction info is returned (but not sure if this really makes sense :D)

**Comment by jpalvarezl** [comment]
Is there maybe a sense on making this endpoint polymorphic? Returning different types for Transfers, SettingsChange and Custom?

**Comment by rmeissner** [comment]
I would not make it fully polymorphic as most of the information is present in different combinations. Therefore I proposed to use the transaction info, which is polymorphic.

**Comment by rmeissner** [comment]
Question:
What should missing confirmations be. Currently I return a `signers` field that corresponds to the safe owners, but maybe we should only return owners that have not signed yet and if the transaction is executed return an empty array as this information cannot always be considered correct for the past.

**Comment by jpalvarezl** [comment]
Not sure. I think we need to have a list of who has signed and who hasn't. If it's truly UI driven then maybe a list of `Address -> has_signed: bool` could make sense in this situation.
