### ISSUE TITLE
Document edge cases regarding `safeTxHash` calculation for backend services

### ISSUE THREAD

**Issue by jpalvarezl** [gnosis/safe-client-gateway#409]
## Edge case 1 (maybe not so edgy)

- We have a safe that used to be `v1.1.1` issuing a *cancellation transaction*
- The safe updates its mastercopy to `v1.3.0`
- The `cancellation` issued in the past, won't be recognised as such, as we always use the freshest safe state for determining the mastercopy version

### Solution to edge case 1
- Introduce historic state updates of a safe (?)

## ADD MORE

**Comment by rmeissner** [comment]
Will be documented in the contracts repo https://github.com/gnosis/safe-contracts/issues/317
