### ISSUE TITLE
Add `chains_info` endpoints

### ISSUE THREAD

**Issue by jpalvarezl** [gnosis/safe-client-gateway#422]
## Feature

- [x] Fetch and cache `indefinitely` the results returned by https://safe-config.staging.gnosisdev.com/api/v1/chains/
- [x] Expose this endpoint result (and cache it) under an endpoint of our own `https://safe-client.staging.gnosisdev.com/api/v1/chains/`

## Open questions

- ~https://safe-config.staging.gnosisdev.com/api/v1/chains/ endpoint is paginated. Should we exhaust all the pages of data when we request this information?~
  - See comments
- The chain info (either coming from the cache or config service) should be requested on every incoming request to the client GW that is network specific?
  - Yes, this should be cached in redis and if possible in memory

**Comment by rmeissner** [comment]
The info provider should only care about a single chain for most of its functionality, not about all available chains. 

For the case where the clients are requesting a list of chains we will also return a paginated response to the clients, so we will just reuse the same pagination logic.

**Comment by jpalvarezl** [comment]
In that case for a single request to, let's say `balances` then we would have to fetch the single `ChainInfo` from the `chain/{id}` endpoint in the config service?

I would open an issue in the config service repo to include the `internalClusterTxServiceUrl` (can be renamed) in the response to both the `/chains` and `/chain/{id}` endpoint. Would that make sense?

**Comment by rmeissner** [comment]
Please wait with this for now, we should get a better picture first by implementing a first version of interstellar
