### ISSUE TITLE
Network dependent notification endpoints

### ISSUE THREAD

**Issue by jpalvarezl** [gnosis/safe-client-gateway#426]
## Context

Notification related endpoints

- `POST /notifications/devices` - not cached at all
- `DELETE /notifications/devices/{uuid}` - not cached at all
- `DELETE /notifications/devices/{uuid}/safes/{address}` - not cached at all

The client gateway should forward the registration to all required services

## Open questions
- It has to be possible that the signature generated by the client is still valid when the payload is split up for the different services
- Currently it is not defined how to indicate on what chain a Safe is, this needs to be adjusted from the current endpoints.

## Sub-issues
#455 
#454

**Comment by rmeissner** [comment]
This endpoint should be chain independant

**Comment by jpalvarezl** [comment]
Which endpoints specifically do you mean?

AFAICT, `DELETE /notifications/devices/{uuid}/safes/{address}` would need it, so we can identify the safe uniquely.

Additionally, for `POST /notifications/devices` there seem to be 2 variants in the core services documentation for the model passed in the body. Would you simply add a field to both variants called `chain_id: String` ? 

I am not sure I see a way to make all 3 endpoints network independent.

**Comment by rmeissner** [comment]
The dependency for the chain id should not be in the url, but in the post data. It should be possible to register and delete multiple devices/ safes for multiple chains at once.

We should also evaluate if we need all three of these endpoints

**Comment by jpalvarezl** [comment]
This is issue is now duplicated by #454 and #455
