### ISSUE TITLE
Return guard info in safe info endpoint 

### ISSUE THREAD

**Issue by MouazAlzahabi** [gnosis/safe-client-gateway#428]
**Is your feature request related to a problem? Please describe.**
Guards info is not returned as part of safe info endpoint, it's already implemented in transaction service. 

**Describe the solution you'd like**
We need to get the guard info as ExtendedAddressInfo structure, more info in the iOS ticket below

**Additional context**
[Transaction Service implementation](https://github.com/gnosis/safe-transaction-service/issues/268)
[iOS ticket](https://app.zenhub.com/workspaces/safe-multisig---mobile-5c1b98250e13551e8aae81eb/issues/gnosis/safe-ios/1222)

**Comment by tschubotz** [comment]
Related web ticket: https://github.com/gnosis/safe-react/issues/2397

**Comment by jpalvarezl** [comment]
Note: `fallback_handler` is not `Option` we can therefore make it so that we prevent requests for `KnownAddress` when the value is `0x0000000000000000000000000000000000000000`
