### ISSUE TITLE
Add chainId/rawPath information to logging regex

### ISSUE THREAD

**Issue by Uxio0** [gnosis/safe-client-gateway#450]
**Is your feature request related to a problem? Please describe.**
With the unified interface it will be difficult to parse the logs.

**Describe the solution you'd like**
Add `chainId` and path without url resolving the variables `raw_path` (if possible) to the logs: https://github.com/gnosis/safe-client-gateway/blob/301dc3265af56f91546c90f795ee16547a8de4da/src/monitoring/performance.rs#L31

Proposed format:

`log::info!("MT::{}::{}::{}::{}::{}::{}::{}", method, raw_path, delta, status_code, path_data, chain_id)`

**Comment by rmeissner** [comment]
We need to pay attention that the information is backwards compatible, as we will have the current and new implementation running in parallel and we need to be able to display the parsed logs for both in kibana

**Comment by jpalvarezl** [comment]
A current log in interstellar looks like this:
`MT::GET::/v1/chains/<chain_id>/safes/<safe_address>/transactions/history?<page_url>&<timezone_offset>::10612::200` 

Do you mean by path data and raw path data, the path with the `/chains/{chain_id}` segment extracted and included, respectively?

**Comment by rmeissner** [comment]
See https://github.com/gnosis/safe-transaction-service/blob/d7b703c171e3a8295c3985a7dee5a1907228139f/safe_transaction_service/utils/loggers.py for current implementation on transcation service

**Comment by jpalvarezl** [comment]
Log -1 for unavailable `chain_id`

**Comment by jpalvarezl** [comment]
completed #479
