### ISSUE TITLE
Register device for push notifications

### ISSUE THREAD

**Issue by Uxio0** [gnosis/safe-client-gateway#454]
# **Endpoint URL**
`/v1/register/notifications`

# **Proposed payload**

## Request object:
```json
{
   "uuid":"<str | null>",
   "cloudMessagingToken":"<str>",
   "buildNumber":"<sematic-version-str>",
   "bundle":"<str>",
   "deviceType":"<str>",
   "version":"ANDROID|IOS|WEB",
   "timestamp":"<iso-str | null>",
   "safeRegistrations":[
      {
         "chainId":"<stringyfied-int>",
         "safes":[
            "<checksummed-address>"
         ],
         "signatures": ["<str-hex>"]
      }
   ]
}
```

## Response 

No returned object

# **Open for discussion**
- Signing `chainId`? 
- No as the `chainId` is part of the payload, this is not necessary

# **Related**
- Signature calculation: https://github.com/gnosis/safe-transaction-service/issues/190

**Edits**
by @jpalvarezl : changed the type of `chainId` from `<int>` to `<stringyfied-int>`
by @jpalvarezl : added endpoint url
by @jpalvarezl : add result payload
by @jpalvarezl : adjusted nullability of fields
by @jpalvarezl : response section adjusted (no object returned) and array of signature: decisions from refinement

**Comment by biafra23** [comment]
Sample JSON:
```
{
  "uuid": "c50750df-700c-4b17-98ca-b95a5c27ca18",
  "safes": [
    {
      "address": "0x00E17aA063fbDB3BFdEfc2c3b2c13173d2711a35",
      "chainId": 1,
      "signature": "0x4b574e7c729db54b427dd17a6b2ae3481221642a9d61c52a53f77500d98ddc1d739c39dfb117619fb09a20e3f5070d018e62c37f89fb622ae10b56a6be9af5c11b"
    },
    {
      "address": "0x00E17aA063fbDB3BFdEfc2c3b2c13173d2711a36",
      "chainId": 4,
      "signature": "0x4b574e7c729db54b427dd17a6b2ae3481221642a9d61c52a53f77500d98ddc1d739c39dfb117619fb09a20e3f5070d018e62c37f89fb622ae10b56a6be9af5c11b"
    }
  ],
  "cloudMessagingToken": "eWv4Ya6OSaiuDI91S0_C6D:APA91bGpprbGOCa1Qev0h3vlMu2nXa9nWpaL7N9fEcX2G4byZ3TSKXircrMtuWg1H4nSG9Ugu7a7rgY1eDKAR9UaxgaP1egTRj3taqAfAQblApuiWFfRRkyxdD3N23t7wYi9ZBIXZ88Z",
  "bundle": "io.gnosis.safe.debug",
  "version": "2.13.0",
  "deviceType": "ANDROID",
  "buildNumber": "703",
  "timestamp": "1618906387"
}
```

**Comment by jpalvarezl** [comment]
Question regarding the type of `chain_id`, The sample json shows it as a `String` but the json definition shows it as `<int>` . We generally treat it as a `String` in the gw anyway, considering the size of the `int` I would prefer leaving it as a `string` for the sake of simplicity.
