### ISSUE TITLE
Normalise chain dependent paths

### ISSUE THREAD

**Issue by jpalvarezl** [gnosis/safe-client-gateway#457]
## Proposal

For ease of parsing for kibana, readability and restful complaince all chain dependent endpoints should be of the form:

`/v1/chains/<chain_id>/safes/...` 
`/v1/chains/<chain_id>/transactions/...` 
 `etc...`

More generally speaking we want to compose endpoints like so:

`/<<version>>/chains/<chain_id>/<<rest_of_the_old_path>>`

**Comment by Uxio0** [comment]
Agree, that's the cleanest and more Restful way to do it

**Comment by elgatovital** [comment]
will new format and old format coexist for some time or will this be a breaking change?

**Comment by jpalvarezl** [comment]
This would be a breaking change which is hopefully introduced before you support the endpoint so there probably won't be a problem.

**Comment by jpalvarezl** [comment]
closed by #464
