### ISSUE TITLE
Add master copy state to Safe information

### ISSUE THREAD

**Issue by rmeissner** [gnosis/safe-client-gateway#462]
## Feature

The client want to know if the mastercopy of a Safe is up to date. This information should be added to Safe info endpoint

## Proposal

The information could be provided in the form of an `enum`.  

**The current states expected are**
- Up to date 
- Not up to date -> if there is a newer version
- Unknown -> if it is an unknown version

**Additional states could be**
 - Not supported (we need to specify the difference with "Unknown" state)
 - Split “not up to date” into 
   * Required
   * Available

## Open questions

- Where do we get this information on a chain basis? (this can diverge from chain to chain)
- What versions do we allow apps to support? (changes in the signing logic could cause the gw to return invalid data e.g. cancellations)

**Comment by jpalvarezl** [comment]
Done #486

**Comment by rmeissner** [comment]
The following should be considered:

- Up to date -> It is a known version to the backend (aka supported by the backend) and the version is newer than or the same as the recommended version
- Outdated -> It is a known version to he backend and the version is older than the recommended version
- Unknown -> It is a version unknown to the backend

For this we should query the `master-copies` endpoint on the core services to get the supported master copies and `chains` endpoint on the config service to get the recommended version.

**Comment by jpalvarezl** [comment]
How do we retrieve the list of known versions for the backend?

**Comment by jpalvarezl** [comment]
Done #501
