### ISSUE TITLE
Add information about latest Safe version to Safe info endpoint

### ISSUE THREAD

**Issue by rmeissner** [gnosis/safe-client-gateway#472]
Currently it is only detected if an update is available for a Safe (#462) but it would be helpful to also display the information (e.g. link to release) about the latest/ recommended version for this chain.

**Comment by jpalvarezl** [comment]
Would this information be provided by the config service? Or we just manually build the github release link in the gw?

**Comment by fmrsabino** [comment]
The transaction service currently returns

```javascript

GET /api/v1/about/master-copies/

[
  ...
  {
    "address": <string>,
    "version": <string>,
    "deployer": <string>,
    "deployedBlockNumber": <integer>,
    "lastIndexedBlockNumber": <integer>
  }
]
```

The deployer here can be set for example to `Gnosis` or `Circles`. However the safe-react app currently has the following:

https://github.com/gnosis/safe-react/blob/a79a4d16a7eaa69cafa5f9206f9935dca771ea05/src/logic/contracts/api/masterCopies.ts#L30-L32

ie.: they check if the `deployer` is `Circles` or not and depending on that change the release link accordingly.

My concerns:
1. If we add the release page to the `/chains` endpoint of the config service we have two different places where we give information about a `master-copy` (although that's already the case with the `recommendedVersion` field)
2. The transaction service already has a deployer name (which is something external to what lives in the blockchain). We should reevaluate the role of the `master-copies` endpoint in the context of the `safe-config-service`. Maybe some metadata can be moved already to the config service.
