### ISSUE TITLE
Use `AddressEx` everywhere possible

### ISSUE THREAD

**Issue by jpalvarezl** [gnosis/safe-client-gateway#484]
## Feature

Currently, due to potentially causing API breaking changes, we introduced `AddressInfo` wherever we wanted a `KnownAddress` additional contract (or token) info on a Ethereum address.

We would like to use 
```rust
pub struct AddressEx {
    pub value: String,
    pub name: Option<String>,
    pub logo_url: Option<String>,
}
```

Wherever we are using a combination of `address: String` and `address_info: AddressInfo`

## Affected locations with existing AddressInfo

- `SettingsChange` transactions:
  - Every variant with a field is affected 
- `Custom` transactions :
  -  `to` and `to_info` 
- `Creation` transaction: 
  - `creator` and `creator_info`
  -  `implementation` and `implementation_info`
  -  `factor` and `factory_info`
- `Transfer` transactions: 
  - `sender` and `sender_info`
  - `recipient` and `recipient_info`
- In `TransactionDetails::TransactionData`
  - `to` has no `AddressInfo` field, could be expanded
  - `address_info_index` is a `HashMap<String, AddressInfo>`, can be simplified into a `Vec<AddressEx>`  

## New locations with AddressInfo

There are fields for which we don't provide `AddressInfo` yet, and we may need to expand them in the future
 
- In `MultisigExecutionDetails`
  - `executor` field 
  - `signers` and `rejectors`
- In `ModuleExecutionDetails`
  - `address` of the module

**Comment by rmeissner** [comment]
I would change to `AddressEx` everywhere where we have an address, but for `signers` and `rejectors` I would not actually try to load the data and just create an empty one. This way we could add it in the future in all places that we seem fit

**Comment by rmeissner** [comment]
Should we rename `value` to `address`?
