### ISSUE TITLE
Provide latest transaction nonce for clients

### ISSUE THREAD

**Issue by sche** [gnosis/safe-client-gateway#485]
**Is your feature request related to a problem? Please describe.**

Clients need a way to get the latest tx nonce when proposing transactions. On web and iOS it was implemented via `/api/v1/safes/\(safe)/multisig-transactions?limit=1`

As part of removing tx service dependency currently on iOS, we request the first queued transaction and take nonce from it. If there is nothing, we take nonce from the safe info request.

**Describe the solution you'd like**

Richard proposed to get the nonce returned as part of the transaction estimation.

**Describe alternatives you've considered**

TBD

**Comment by jpalvarezl** [comment]
I will follow  @rmeissner suggestion to include this information in the `estimation` endpoint
