### ISSUE TITLE
Make `TokenInfo` entries in the cache chain dependant

### ISSUE THREAD

**Issue by jpalvarezl** [gnosis/safe-client-gateway#505]
We should add different `hset` ids that contain the chain_id

e.g.
`dip_ti_4` for rinkeby

**Comment by rmeissner** [comment]
Relevant code: https://github.com/gnosis/safe-client-gateway/blob/e1dc52675e755dd4389174f68a1d7dee04d8469a/src/providers/info.rs#L225-L264

**Comment by jpalvarezl** [comment]
Done #506
