### ISSUE TITLE
Add support for Block Explorer URI templates

### ISSUE THREAD

**Issue by fmrsabino** [gnosis/safe-client-gateway#515]
Different block explorers might have different ways of addressing an `address` or `tx_hash` or any other _addressable_ entity.

Given the current scope of the block explorers that we currently support, we assume that most of this _addressable entities_ can be set on the path of the url.

Therefore we propose the following change:

```javascript
GET /v1/chains/<chain_id>/

{
  ...
  blockExplorerUriTemplate: {
    "address": <string>, // eg.: https://etherscan.io/address/{{address}}
    "txHash": <string> // eg.: https://etherscan.io/tx/{{txHash}}
  }
}
```

The clients would then replace the agreed pattern with its correct value.

### 1. What would be the pattern?

I thought about having `{{address}}`, or `{{txHash}}` but this needs to be aligned with the client teams.

### 2. What should be initial level of support for the different templates?

I'm under the assumption that the clients use a block explorer for both the `address` and `txHash`. Is there any other entity that can and should be added to the payload? (eg.: block number: `https://etherscan.io/block/{{blockNumber}}`)

@gnosis/safe-android @gnosis/safe-ios @gnosis/safe-web @gnosis/safe-services

**Comment by sche** [comment]
LGTM.
Should we use the plural form for `blockExplorerUriTemplates`?

**Comment by fmrsabino** [comment]
> LGTM.
> Should we use the plural form for `blockExplorerUriTemplates`?

Isn't it already that way? blockExplorerUriTemplate**s**

Or maybe I misunderstood your question 😅

**Comment by sche** [comment]
Yes, I mean why not `blockExplorerUriTemplate`

**Comment by fmrsabino** [comment]
I agree. Updated:

```javascript
GET /v1/chains/<chain_id>/

{
  ...
  blockExplorerUriTemplate: {
    "address": <string>, // eg.: https://etherscan.io/address/{{address}}
    "txHash": <string> // eg.: https://etherscan.io/tx/{{txHash}}
  }
}
```
