### ISSUE TITLE
ERC20 transfer not decoded as such

### ISSUE THREAD

**Issue by tschubotz** [gnosis/safe-client-gateway#518]
**Describe the bug**
ERC20 transfer not decoded as such

(In case this is not a bug, I'm wondering why the tx is not marked as ERC20 transfer.)

**To Reproduce**

1. Open https://gnosis-safe.io/app/#/safes/0x4a5a0f167880da1d268b3cbfc031444aad61e5d6/transactions or https://safe-client.mainnet.gnosis.io/v1/safes/0x4a5A0F167880dA1d268B3CBfc031444AaD61e5D6/transactions/queued/

-> Tx is marked as custom tx

**Expected behavior**
The transfer is decoded as ERC20.

**Additional context**

**Comment by jpalvarezl** [comment]
Hi @tschubotz now it appears to be classified correctly. Could it be that at the time of opening the issue the token metadata was not available yet? In that case we would need to wait for the caches to expire, as we would indeed, classify it as custom and that would be cached for a while, even if the `TokenInfo` would become available in that time. As far as I know there isn't any webhook for `NewToken` or something like that. Could be something to incorporate in the backend :thinking:

**Comment by tschubotz** [comment]
> Could it be that at the time of opening the issue the token metadata was not available yet?

Not sure, I didn't check that, will do next time in case something like this appears again.

**Comment by jpalvarezl** [comment]
Let's keep an eye on this
