### ISSUE TITLE
Add GW version of the `/owners/{address}/safes/` endpoint

### ISSUE THREAD

**Issue by jpalvarezl** [gnosis/safe-client-gateway#529]
## Context

The `/owners/{address}/safes/` endpoint is directly queried by the web app is an endpoint known to be problematic due to the heavy load it puts on the database. 

## Feature

Create a cached endpoint with backend/service models decoupled from each other under

`GET /v1/chains/<chain_id>/owners/<address>/safes` 

## Open questions

What webhook payload invalidates this endpoint in case of changes?

We don't have one, we cache for 1 minute

**Comment by rmeissner** [comment]
How is this issue related to https://github.com/gnosis/safe-client-gateway/issues/449

**Comment by jpalvarezl** [comment]
In its conception it was not. This issue is just a reaction to the service outage. This endpoint was reported to be used directly from the core services and it is also very heavy on the resource side of things. We are just trying to mitigate the load by providing this and heavily cache it.

**Comment by rmeissner** [comment]
If this endpoint causes issues we should remove it on the core production services (or rate limit it or prevent external traffic) as it is not used by any of our production interfaces

**Comment by jpalvarezl** [comment]
I've moved this back to `review spec` so we can maybe include the fields requested by Ivan and address the open questions.

**Comment by rmeissner** [comment]
Only for staging or also in production?

**Comment by katspaugh** [comment]
Frontend ticket: https://github.com/gnosis/safe-react-gateway-sdk/issues/12
