### ISSUE TITLE
Verify no leaking requests on heavy load

### ISSUE THREAD

**Issue by jpalvarezl** [gnosis/safe-client-gateway#531]
## Context

Ever since we introduced the usage of `async/await` concurrent requests that result on a cache miss would get passed on to the core services. This prevents us from leveraging the CGW as a caching layer over the core services on heavy duty scenarios. Particularly problematic for endpoints that put a lot of strain on the database.

## Proposal

This topic requires some research as to what is the standard handling of this sort of situation (concurrent access to a redis instance).

The current proposal would implement:
- We introduce a redis connection pool
- A locking mechanism over our redis connection pool
- new requests wait until a new connection can be issued by the pool

## References

We don't have tests allowing this sort of integration testing, however in order to simulate a highly concurrent setting, we can leverage the following:

- Add mock json of the safe config service that would allow us to point to mock servers of the tx service running locally
- Use a mock server to simulate the particular instance of the core service ([Link to suggestion](https://github.com/http-party/http-server))
- Stress the local instance of the GW, with high levels of concurrency, in order to verify that we do in fact route the traffic into our redis and not leak requests ([Link to tool](https://github.com/fcsonline/drill))
- Verify that our local tx service mock is never reached

## Further reading

https://blog.logrocket.com/using-redis-in-a-rust-web-service/

**Comment by rmeissner** [comment]
In my opinion it is expected that under heavy load we currently have some duplicate requests.

**Comment by jpalvarezl** [comment]
What we saw as a risk during last week, was that if we have concurrent duplicate requests that result in cache non-hits, all of them would be allow to request against the core-service. Introducing some form of locking mechanism over a pool of connections to redis could help address this. This issue would allow to setup the environment to develop that.

**Comment by rmeissner** [comment]
That is why I said with the current implementation. 

Before changing to something where we have a lock in redis for ongoing requests and a waiting logic that checks if the request was done, it doesn't make sense to test it. So we should link an issue here that would implement this.

**Comment by rmeissner** [comment]
Also since it isnproposed to add a mock service for the core services, why not also for the config service? 

Would another first step be to add integration tests for the client gateway based on which this is tested?

**Comment by jpalvarezl** [comment]
That would be a good alternative to adding test data in staging, but as the setup was cheaper, by simply adding a `chain_id` for our testing, I simply proposed the "cheapest" option

**Comment by jpalvarezl** [comment]
> That is why I said with the current implementation.
> 
> Before changing to something where we have a lock in redis for ongoing requests and a waiting logic that checks if the request was done, it doesn't make sense to test it. So we should link an issue here that would implement this.

I would be happy to hear about this in more detail because I don't think I follow your meaning.

**Comment by jpalvarezl** [comment]
to clarify I want to make sure how much stress on the system it takes to bypass redis and hit the core service even for requests that should be fetched from the cache, as last week the core service seemed to receive more requests than they should. This is simply a exploratory task.

**Comment by rmeissner** [comment]
Does it really make sense to do this in the described way? You can easily estimate this, by looking at internal requests times (as this primarily depends on how fast the core services respond).

**Comment by jpalvarezl** [comment]
To me it does seem to make sense, as I don't think I can come up with that estimation easily.

**Comment by Uxio0** [comment]
I think this would take some time to set up and test, and I think it makes sense just testing it with regular rust tests

**Comment by fmrsabino** [comment]
Decided that we should create an issue about not firing multiple requests to the core services for the same cgw request.
