### ISSUE TITLE
Mark 1.1.1 and 1.2.0 mastercopies as UpToDate till the update from 1.1.1 to 1.3.0 is implemented on web

### ISSUE THREAD

**Issue by liliya-soroka** [gnosis/safe-client-gateway#541]
According to https://gnosisinc.slack.com/archives/CQB729LLF/p1627461376127700 1.1.1 and 1.2.0 should be returned as UpToDate till https://github.com/gnosis/safe-react/issues/2572 is implemented on web

**Comment by liliya-soroka** [comment]
closed 
1.1.1 is uptodate version

**Comment by rmeissner** [comment]
This is not a client gateway issue. This is a setting in the config service admin.

**Comment by fmrsabino** [comment]
@liliya-soroka I will close this issue since this is related with the data returned on staging and it is not an application issue of the CGW
