### ISSUE TITLE
`baseGas` and `safeTxGas` types into `String`

### ISSUE THREAD

**Issue by jpalvarezl** [gnosis/safe-client-gateway#543]
Change the types of `base_gas` and `safe_tx_gas` in the `MultisigExecutionDetails` to `String`

**Comment by rmeissner** [comment]
Next: check if this is a breaking change

**Comment by jpalvarezl** [comment]
Android & iOS: not a breaking change
Web: breaking change; however easliy solvable

**Comment by liliya-soroka** [comment]
@jpalvarezl , please, ping me when it will be on staging to check the web app
