### ISSUE TITLE
Balances, Safe info and txs don't load

### ISSUE THREAD

**Issue by tschubotz** [gnosis/safe-client-gateway#546]
**Describe the bug**
Balances, Safe info and txs don't load

**To Reproduce**
- Open any Safe on mainnet prod, e.g. https://gnosis-safe.io/app/#/safes/0xA063Cb7CFd8E57c30c788A0572CBbf2129ae56B6/ 
-> Doesn't load.

**Expected behavior**
Balances and txs show up

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser Firefox
 - Version ?

**Additional context**
- https://safe-client.mainnet.gnosis.io/v1/safes/0xA063Cb7CFd8E57c30c788A0572CBbf2129ae56B6/ -> 503
- https://safe-transaction.gnosis.io/api/v1/safes/0xA063Cb7CFd8E57c30c788A0572CBbf2129ae56B6/  -> fine

**Comment by jpalvarezl** [comment]
Just some notes to myself:

The unified version works: https://safe-client.gnosis.io/v1/chains/1/safes/0xA063Cb7CFd8E57c30c788A0572CBbf2129ae56B6/

This endpoint also uses the `all-transactions` endpoint for calculating the `txHistoryTag`
