### ISSUE TITLE
Docker compose - Redis connection issue - Can't start web container

### ISSUE THREAD

**Issue by air3ijai** [gnosis/safe-client-gateway#548]
**Describe the bug**
Web server container can't connect to the Redis

**To Reproduce**
- Ubuntu 18.04.5 LTS
- Install Docker-compose
- Clone repository
- Create .evn from .env.sample
- Build images
- Run images
```
web_1    | thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Redis URL did not parse', src/cache/redis.rs:13:51
web_1    | note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
safeclientgateway_web_1 exited with code 101
```

**Expected behavior**
Images should run and work

**Additional context**
- Change in docker-compose.yml: **- REDIS_URL="redis://redis" --> - REDIS_URL="redis://127.0.0.1"**
```web_1    | thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Redis URL did not parse', src/cache/redis.rs:13:51```
- Change in docker-compose.yml: **- REDIS_URL="redis://redis" --> - REDIS_URL="redis://127.0.0.1:6379"**
```web_1    | thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Redis URL did not parse', src/cache/redis.rs:13:51```
- Change in docker-compose.yml: **- REDIS_URL="redis://redis" --> - REDIS_URL=redis://127.0.0.1:6379**
```web_1    | thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error(Some("Connection refused (os error 111)"))', src/cache/redis.rs:14:48```

Redis container works and can be accessed from Docker host
```
redis-cli -h localhost -p 6379 ping
PONG
```

**Comment by jpalvarezl** [comment]
This is addressed in #532, we are working to bring this to a mergeable state.
