### ISSUE TITLE
Refactor extraction of params from DataDecoded

### ISSUE THREAD

**Issue by rmeissner** [gnosis/safe-client-gateway#55]
Currently it is quite tedious to extract params from DataDecode with fallbacks (e.g. `to` and `_to`). It would be nice to have a easy way to handle this.

### Note
It should be safer to use the position of the argument rather than the name of the argument.

**Comment by jpalvarezl** [comment]
I got as feedback from iOS specifically that they have types defined for `SettingsChange` instead of using `dataDecoded` directly. Maybe we should factor in, including some types and enums into the `SettingsChange` definition.

**Comment by rmeissner** [comment]
this would be a different issue, and question would be if they want this in a first version then we should add this to soon, as Android would require changes there too.

Theoretically we can also have this in a v2, but it would be good to know. I would suggest to create a separate issue for that.
