### ISSUE TITLE
Asset list and balances don't load for certain Safes on Polygon

### ISSUE THREAD

**Issue by ennisjo** [gnosis/safe-client-gateway#551]
**Describe the bug**
https://gnosisinc.slack.com/archives/CQB729LLF/p1628239048220700?thread_ts=1628238497.219300&cid=CQB729LLF appears to be timing out

**To Reproduce**
Try to load up the Safe on the react UI or through the transactions API 

**Expected behavior**
Assets are loaded in the Safe react UI and the transaction API link does not timeout

**Desktop (please complete the following information):**
 - OS: iOS
 - Browser Chrome

**Additional context**

**Comment by jpalvarezl** [comment]
The optimizations that could be done to this point were done. The only actionable thing left to do in the CGW is to increase the `BALANCES_REQUEST_TIMEOUT` or the `COLLECTIBLES_REQUEST_TIMEOUT` . The core services timeout at 90 secs but the CGW currently times out at 20.

**Comment by jpalvarezl** [comment]
Requested devOps to set `BALANCES_REQUEST_TIMEOUT` to `60000` milliseconds, as the default value `20000` was preventing the assets from loading for the safe mentioned in the thread.

**Comment by jpalvarezl** [comment]
The requests go through now, but we will continue to monitor the situation.
