### ISSUE TITLE
Return JSON for /transactions/{safe_address}/propose

### ISSUE THREAD

**Issue by katspaugh** [gnosis/safe-client-gateway#554]
## Overview
The transaction creation request has a weird empty response with a 200 code. It would be nice to always reply with JSON to any (successful) request to the API.

## Requirements
`/transactions/{safe_address}/propose` should return this response in case of success:
```
{ "safeTxHash": "0x1234" }
```

Please also check if any other POST-requests return an empty response.

**Comment by rmeissner** [comment]
Could you outline why a response is required? If we follow REST we should return the created object (a multisig transaction in this case), wouldn't that make more sense)?

**Comment by katspaugh** [comment]
It would be just nice to have a consistent response type across the endpoints. In the linked SDK PR we had to introduce and `if` checking if the response is supposed to be parsed as JSON.

Returning the created object would be even better, sure. We could then link directly to a transaction details screen (which we don't have yet but there's a ticket for it).

**Comment by mikheevm** [comment]
https://stackoverflow.com/a/28951049/7820085

**Comment by jpalvarezl** [comment]
The core services endpoints technically don't return anything for either `confirmations` and `proposal`. We could mimic the behaviour of the `post_confirmation` endpoint of the gw, where after posting to the core services we invalidate our redis and fetch the tx_details. IMO, If this is not urgent, I would implement this once we've addressed some caching issues in the core services.

**Comment by katspaugh** [comment]
@jpalvarezl where can I test this?
