### ISSUE TITLE
Safe creation transaction

### ISSUE THREAD

**Issue by DmitryBespalov** [gnosis/safe-client-gateway#56]
**Is your feature request related to a problem? Please describe.**
Currently, the safe creation transaction is available as a separate endpoint in the transaction service. 
For example:  https://safe-transaction.gnosis.io/api/v1/safes/0xA063Cb7CFd8E57c30c788A0572CBbf2129ae56B6/creation/

In order to integrate it into the transaction list on the client, the client app needs then to make additional request when the last page of the all-transactions is reached, and then augment the response with the response from the endpoint above.

**Describe the solution you'd like**
The solution would be to receive the safe creation transaction from the transactions response. If the creation endpoint response structure is preserved, then we need to augment it at least with a new "txType" for the creation transaction. Alternatively, if there's a way to format the response as another 'settings' transaction, that could also work.

**Describe alternatives you've considered**
Alternative: to request the creation transaction data from the client

**Additional context**
This appeared as part of working on requirements for the issue https://github.com/gnosis/safe/issues/315

**Comment by rmeissner** [comment]
Implementations note:
The information will be returned in the list (aka create new transaction info object with a simple id), but it will not be possible to request information for this via the details endpoint.

Be aware that there are cases where creation info cannot be provided by the backend, in this case we need to simulate a response.

**Comment by jpalvarezl** [comment]
It seems like the accepted design matches one for one the response from the transaction service. I will reuse the object for details and have a stripped down version for summary (list item). Unless there is any objections.

**Comment by rmeissner** [comment]
I thought we don't provide details? How would you provide it? As a separate endpoint? How does it align to the other transaction details?

**Comment by rmeissner** [comment]
Also could we define the tasks that we want to perform (just as a checklist, e.g. map creation data to summary, load creation data on last page, ...) and add a proposal for the creation summary here?

**Comment by jpalvarezl** [comment]
Sorry I think I may have mixed things up from our talk yesterday.

[ ] Define `TransactionInfo::Creation`
[ ] Define `struct CreationTransaction`

Proposal:
```rust
pub struct Creation {
    pub creator: String,
    pub transaction_hash: String,
    pub master_copy: Option<String>,
    pub factory: Option<String>,
}
```

```rust
let creation_from_above_block = Creation { ... };
TransactionSummary {
  id: String::from("creation"), //clients ignore
  timestamp: creationDto.created.clone(), //creationDto correspond to the request from the backend
  tx_status: TransactionStatus::Success, //otherwise we wouldn't be here
  tx_info: creation_from_above_block,
  execution_info: None,
}
```

**Comment by jpalvarezl** [comment]
The clients is then free to serialise this object and pass it on to the details or request the backend for the data themselves.

**Comment by rmeissner** [comment]
Looks good. What about your idea to add the safe address to the id, just in case in the future we want to do something? Might be premature optimization, but it is not that hard :P.

**Comment by jpalvarezl** [comment]
Ah yeah sure, let's do that.
