### ISSUE TITLE
Architecture documentation

### ISSUE THREAD

**Issue by air3ijai** [gnosis/safe-client-gateway#564]
Hello,

We just started to explore Gnosis Safe platform and build infrastructure for it:
1. Safe-relay
2. Safe-transaction
3. Safe-config
4. Safe-gateway

We already deployed using docker-compose 1-3 and did some performance tests. Gateway is remained.

After fixing an issue with the Redis connection https://github.com/gnosis/safe-client-gateway/issues/548 we finally started it and now we are trying to test its performance to build an appropriate infrastructure.

From repository:
```Clients --> Safe Gateway --> Safe Transaction```

Our container opened port 8000 but we can't connect to it. It is the HTTP service?

Where we can find more information about Gnosis Safe components architecture and specially about how Safe Gateway is connected to other components to understand how can we test it.

Thank you!

**Comment by rmeissner** [comment]
As part of this we will take the following steps:
- [ ] Document current architecture
- [ ] Create `docker-compose` to run the whole setup with local node (for L2 optimized contracts)
- [ ] Document steps what needs to be done to register a new chain
  - Register webhook

**Comment by air3ijai** [comment]
@rmeissner, it seems that the initial issue with filed connection was solved:
[docker-compose.yml](https://github.com/gnosis/safe-client-gateway/blob/main/docker-compose.yml)
```
 web:
    ports:
>      - "8000:3666"
<      - "8000:8000"
```
[.env.sample](https://github.com/gnosis/safe-client-gateway/blob/main/.env.sample)
```
> ROCKET_ADDRESS=127.0.0.1
< ROCKET_ADDRESS=0.0.0.0
```
And now we are able to connect to the service using API mentioned on the [Client Gateway Wiki](https://gnosis.github.io/safe-client-gateway/docs/).

But some questions related to the service still remained:
1. Why Nginx is not used in front of Client Gateway like it is done for Relay/Transaction/Config services?
2. How can we specify Redis DB? Now we see the following `REDIS_URL=redis://127.0.0.1:6379` - it is 0 by default?

**Comment by air3ijai** [comment]
Based on the experiments, we can set `REDIS_URL=redis://127.0.0.1:6379/2` to point the the DB2.

We also started to use Nginx in front of Gateway for HTTPS. Can we configure gateway itself for HTTPS connection?

And one more question related to the architecture
From documentation: https://docs.gnosis.io/safe/docs/services_client_gateway/
> The Safe client gateway is a gateway between the Safe clients on the respective platforms (Android/ iOS/ web) and the Safe backend services (Transaction service including Ethereum nodes)

It looks like:
Client --> Gateway --> Transaction

How Gateway connect to the Transaction Service? Is there any key in the [.env file](https://github.com/gnosis/safe-client-gateway/blob/main/.env.sample)?

**Comment by jpalvarezl** [comment]
I will close this issue as the remaining questions were answered in discord in the archived thread `Gateway-TransactionService`.

For future reference: 
- We've documented our architecture and intended use in this [wiki page](https://app.gitbook.com/@gnosissafe/s/documentation/backend/service-architecture) . We will continue to add more info to the article
- We have started work to prepare a `docker-compose.yaml` file , it is still at a very early stage but we want to make it as simple to use as possible. You can find the repo [here](https://github.com/gnosis/safe-infrastructure)

**Comment by air3ijai** [comment]
@jpalvarezl, thank you for the updates and infrastructure repository, looks very good!

I have tried to open Wiki page - https://app.gitbook.com/@gnosissafe/s/documentation/backend/service-architecturem but got 'Not Authorized' error and the following URL: https://app.gitbook.com/o/-MhyDtGxUyODu7d4sgda/s/-MhyEZtd5TVytPJtyS7v-2910905616/backend/service-architecture.

I used my GitHub account to login to the GitBook.

**Comment by jpalvarezl** [comment]
Sorry for getting back to you late on this. I think this was moved to the public docs in gitbook, but if the issue persists I will look into it.

**Comment by air3ijai** [comment]
Just tried again to open your link - [wiki page](https://app.gitbook.com/@gnosissafe/s/documentation/backend/service-architecture) and got same error
<img width="1106" alt="Screenshot 2021-12-02 at 10 51 18" src="https://user-images.githubusercontent.com/88528265/144389242-8f6a4ead-54c3-483d-b23e-c67927a5674a.png">
