### ISSUE TITLE
Add forward endpoint for `/safe-apps` from the config servcie

### ISSUE THREAD

**Issue by jpalvarezl** [gnosis/safe-client-gateway#595]
## Feature

Implement a forward endpoint for the `/safe-apps` config service endpoint.

## Context

The current payload from the config service is as follows:

```json
[
  {
    "id": 0,
    "url": "string",
    "name": "string",
    "iconUrl": "string",
    "description": "string",
    "chainIds": [
      0
    ],
    "provider": {
      "url": "string",
      "name": "string"
    }
  }
]
```

Where the request is (in staging) looks like `https://safe-config.staging.gnosisdev.com/api/v1/safe-apps/?chainId=1`

`chainId` is an integer query parameter for which we filter apps available in certain networks.

## Proposal

We stringgify all the fields that are currently ints, namely `id` and the array `chainIds` turns into an array of stringyfied-ints, like so:

```json
[
  {
    "id": "0",
    "url": "string",
    "name": "string",
    "iconUrl": "string",
    "description": "string",
    "chainIds": [
      "0"
    ],
    "provider": {
      "url": "string",
      "name": "string"
    }
  }
]
```

The request against the config service is cached for as long as we cache `ChainInfo` we would also cache the response but set the duration to something negligible (to avoid issues with flushing).

The CGW **accepts and forwards** the `chainId` query parameter to the config service.

## Questions

Do we need a new payload for the flush endpoint in the CGW to invalidate changes to the underlying data in this endpoint? Do we re-use the `InvalidationPattern::Chains` and change it to be `InvalidationPattern::ConfigService` to simplify things?

**Comment by jpalvarezl** [comment]
More context: https://gnosisinc.slack.com/archives/CQB729LLF/p1630318000094600

**Comment by jpalvarezl** [comment]
If we align, then we would loose the posibility of filtering for multiple values. But I agree, it would be nice to be able to do so.

**Comment by rmeissner** [comment]
> we would lose the posibility of filtering for multiple values

Is this currently possible?

**Comment by jpalvarezl** [comment]
Yes, like so: `https://safe-config.staging.gnosisdev.com/api/v1/safe-apps/?chainId=1&chainId=137`

**Comment by rmeissner** [comment]
This only filters by the second value for me

**Comment by jpalvarezl** [comment]
I get the following result from that request (https://safe-config.staging.gnosisdev.com/api/v1/safe-apps/?chainId=1&chainId=137): 


```json
[
  {
    "id": 26,
    "url": "https://curve.fi",
    "name": "Curve",
    "iconUrl": "https://curve.fi/logo-square.svg",
    "description": "Decentralized exchange liquidity pool designed for extremely efficient stablecoin trading and low-risk income for liquidity providers",
    "chainIds": [
      1,
      137
    ],
    "provider": null
  },
  {
    "id": 24,
    "url": "https://cloudflare-ipfs.com/ipfs/QmdVaZxDov4bVARScTLErQSRQoxgqtBad8anWuw3YPQHCs",
    "name": "Transaction Builder",
    "iconUrl": "https://cloudflare-ipfs.com/ipfs/QmdVaZxDov4bVARScTLErQSRQoxgqtBad8anWuw3YPQHCs/tx-builder.png",
    "description": "A Safe app to compose custom transactions",
    "chainIds": [
      1,
      4,
      56,
      100,
      137,
      246,
      73799
    ],
    "provider": null
  },
  {
    "id": 11,
    "url": "https://app.1inch.io",
    "name": "1inch.exchange",
    "iconUrl": "https://app.1inch.io/assets/images/1inch.svg",
    "description": "The most efficient defi aggregator",
    "chainIds": [
      1,
      56,
      137
    ],
    "provider": {
      "url": "https://1inch.exchange",
      "name": "1inch corporation"
    }
  },
  {
    "id": 30,
    "url": "https://paraswap.io",
    "name": "ParaSwap",
    "iconUrl": "https://paraswap.io/paraswap.svg",
    "description": "ParaSwap allows dApps and traders to get the best DEX liquidity by aggregating multiple markets and offering the best rates",
    "chainIds": [
      1,
      56,
      137
    ],
    "provider": null
  },
  {
    "id": 25,
    "url": "https://cloudflare-ipfs.com/ipfs/QmTpLhxSiD1H94BFxeV2P6RfJf6EyCxxUCVYpcDffyMmmZ",
    "name": "WalletConnect",
    "iconUrl": "https://cloudflare-ipfs.com/ipfs/QmTpLhxSiD1H94BFxeV2P6RfJf6EyCxxUCVYpcDffyMmmZ/wallet-connect.svg",
    "description": "Allows your Gnosis Safe Multisig to connect to dapps via WalletConnect.",
    "chainIds": [
      1,
      4,
      56,
      100,
      137,
      246,
      73799
    ],
    "provider": null
  }
]
```

**Comment by jpalvarezl** [comment]
which appears to return `chainIds` containing both `1` and `137`

**Comment by jpalvarezl** [comment]
@rmeissner is right, swapping the order of the query params yields a different response (just `chainId=1`) 

https://safe-config.staging.gnosisdev.com/api/v1/safe-apps/?chainId=137&chainId=1

**Comment by fmrsabino** [comment]
> We stringgify all the fields that are currently ints, namely id and the array chainIds turns into an array of stringyfied-ints, like so

I would open a ticket on the `config-service` for this instead. Our model/data representation should be the same across services.

> The request against the config service is cached for as long as we cache ChainInfo we would also cache the response but set the duration to something negligible (to avoid issues with flushing).

Just as a FYI, the safe-apps are currently cached for 10 minutes on the `config-service`.
Question: I don't understand the relationship between the safe-apps and `ChainInfo` here. Even on the `config-service` they are completely separate and no relationship exists between these two endpoints and respective data. I would consider not caching this data at all or maybe have it configurable to enable or disable caching on demand.

**Comment by fmrsabino** [comment]
> @rmeissner is right, swapping the order of the query params yields a different response (just `chainId=1`)
> 
> https://safe-config.staging.gnosisdev.com/api/v1/safe-apps/?chainId=137&chainId=1

Yes. We have a test that demonstrates this on the config service:
https://github.com/gnosis/safe-config-service/blob/3604ad565ffbc6a6f1b32ebaac44f3a4cdff839d/src/safe_apps/tests/test_views.py#L158-L177

**Comment by fmrsabino** [comment]
> Should we align the url pattern with the current chain specific urls? @fmrsabino do the clients use this without the chain filter?

@rmeissner Sorry didn't see this comment. The clients use the endpoint with the `?chainId` – https://github.com/gnosis/safe-react/blob/e7b440cc06756ec578de9778d8b2a1d109126c2d/src/logic/configService/index.ts#L21
