### ISSUE TITLE
Add uncached version of the `/about` endpoint

### ISSUE THREAD

**Issue by jpalvarezl** [gnosis/safe-client-gateway#602]
## Context
Currently the `/v1/chains/{chain_id}/about` endpoint is cached for 15 minutes.

## Feature
We should add an endpoint that is chain independent `/about` returning information purely about the CGW itself.

```json
{
  "name": "safe-client-gateway",
  "version": "3.2.1",
  "buildNumber": "1099"
}
```

This would allow us to verify deployments more easily and have a real time look at what is the current state of the running instance.

**Comment by fmrsabino** [comment]
This would be a nice addition! My suggestion is to have the path as `/v1/about`. I don't think we'd need `instance` in this case. This would also match what the core-services and config-service do
