### ISSUE TITLE
New tx not appearing in queue immediately

### ISSUE THREAD

**Issue by katspaugh** [gnosis/safe-client-gateway#607]
**Describe the bug**
Requesting the tx queue shortly after proposing a transaction returns a list w/o the new transaction.

**To Reproduce**
- Call URL https://safe-client.gnosis.io/v1/chains/4/transactions/0x9B5dc27B104356516B05b02F6166a54F6D74e40B/propose
- Once it responds, call URL https://safe-client.gnosis.io/v1/chains/4/safes/0x9B5dc27B104356516B05b02F6166a54F6D74e40B/transactions/queued

**Expected behavior**
The queue should contain the newly created transaction.

**Additional context**
Proposed tx:
<img width="1328" alt="Screenshot 2021-09-02 at 16 49 33" src="https://user-images.githubusercontent.com/381895/131865736-1e4984be-efa4-4846-9800-9062aa39f8f6.png">
Queue:
<img width="878" alt="Screenshot 2021-09-02 at 16 49 43" src="https://user-images.githubusercontent.com/381895/131865762-54578604-8aee-4d9d-8109-c41baa41f1db.png">

Eventually, the transaction does appear in the history response (after repeatedly requesting it for ~15 seconds), w/o ever popping up in the queue.

**Comment by jpalvarezl** [comment]
Could not reproduce. I think this could have a been a transient service load related issue. If this becomes the norm then let's re-open this issue.

**Comment by katspaugh** [comment]
We'll be now redirecting directly to the created tx, so this doesn't matter anymore. 😄
Thanks for checking!
