### ISSUE TITLE
Add L2 field to ChainInfo

### ISSUE THREAD

**Issue by fmrsabino** [gnosis/safe-client-gateway#615]
A new field was added in the `config-service` to describe if the chain is a Layer 2 chain. This field should be consumed and exposed to the clients. See https://github.com/gnosis/safe-config-service/pull/225

@gnosis/safe-web

**Comment by fmrsabino** [comment]
Available on `staging`: https://safe-client.staging.gnosisdev.com/v1/chains

**Comment by katspaugh** [comment]
Looks like it's still cached or something, I can't see the l2 flag.

**Comment by fmrsabino** [comment]
> Looks like it's still cached or something, I can't see the l2 flag.

Should be available now.

**Comment by katspaugh** [comment]
It works, thank you @fmrsabino ✅
