### ISSUE TITLE
Introduce `transactionService` and `vpcTransactionService` toggle env var

### ISSUE THREAD

**Issue by jpalvarezl** [gnosis/safe-client-gateway#629]
### Feature

From `v3.6.0` local development won't be possible as we would be using VPC internal URLs even in staging.

We need an easy way to use the external URL for the services.

### Proposal

Introduce env var `USE_EXTERNAL_TX_SERVICE_URI=<bool>` as a mean to toggle between using `transactionService` and `vpcTransactionService` URLs in the `core_uri!` macro.

**Comment by fmrsabino** [comment]
Maybe we can take a look into https://doc.rust-lang.org/reference/conditional-compilation.html

Specially into `debug_assertions`.

And then we can have the same macro declared twice (only one will be compiled):

```rust
#[cfg(debug_assertions)]
macro_rules! core_uri {
  ...
}

#[cfg(not(debug_assertions))]
macro_rules! core_uri {
  ...
}
```
