### ISSUE TITLE
An endpoint to get a single known address name

### ISSUE THREAD

**Issue by katspaugh** [gnosis/safe-client-gateway#652]
## Description
For [#2817](https://github.com/gnosis/safe-react/issues/2817), we need an endpoint that would return an `AddressEx` for a given address.

E.g. request: `/contracts/0x35457547457563478657`
Response: `{"value": "0x35457547457563478657", "name": "CowSwap Exchange"}`

### Note
As per @jpalvarezl's comment in #2817, this is for situations like Outgoing Transaction Form, where we don't have any backend context around an address.

**Comment by jpalvarezl** [comment]
Duplicates already implemented issue: https://github.com/gnosis/safe-client-gateway/issues/700
