### ISSUE TITLE
Create wiki with api sample

### ISSUE THREAD

**Issue by rmeissner** [gnosis/safe-client-gateway#67]
- [x] Example of transaction list with different types
- [x] Examples of different detail responses

**Comment by jpalvarezl** [comment]
I have added a provisional wiki page for the purpose of the Engineering presentation: https://github.com/gnosis/safe-client-gateway/wiki

**Comment by jpalvarezl** [comment]
https://github.com/gnosis/safe-client-gateway/wiki 

Let's re-open the issue if the samples I added are insufficient.
