### ISSUE TITLE
Add disabled wallets to ChainInfo

### ISSUE THREAD

**Issue by fmrsabino** [gnosis/safe-client-gateway#674]
The clients require a list of incompatible wallets for each chain – if a wallet is not compatible with a given chain then that wallet won't be used on the client side for that chain.

This assumes that a wallet by default is supported until it is part of this list.

```javascript
GET /api/v1/chains

[
  {
    "chainId": <string>,
    "disabledWallets": [<string>] // eg.: [ "metamask", "trust"]
    ...
  }
]
```

cc/ @gnosis/safe-web @gnosis/safe-services

**Comment by katspaugh** [comment]
Works well, thanks Fred!

One question tho: is it normal that whenever I edit the test wallet (just editing its name), it creates a new entry instead of updating the existing one?

**Comment by fmrsabino** [comment]
> Works well, thanks Fred!
> 
> One question tho: is it normal that whenever I edit the test wallet (just editing its name), it creates a new entry instead of updating the existing one?

That is correct and thanks for pointing this out. Basically the `name` of a `Wallet` is a primary key. This means that it is `read_only`. Changing the primary key then creates a new entry.
