### ISSUE TITLE
Add features field to ChainInfo

### ISSUE THREAD

**Issue by fmrsabino** [gnosis/safe-client-gateway#675]
Each chain should provide a list of features that the client can assume as enabled if provided for that chain.

The available features are `ERC721`, `ERC1155`, `SAFE_APPS`, `CONTRACT_INTERACTION`, `DOMAIN_LOOKUP` and `SPENDING_LIMIT`.

```javascript
GET /api/v1/chains

[
  {
    "chainId": <string>,
    "features": [<string>] // eg.: [ "ERC721", "SAFE_APPS"]
    ...
  }
]
```

cc/ @gnosis/safe-web @gnosis/safe-services

**Comment by fmrsabino** [comment]
@gnosis/safe-web `features` are now available on `staging`

`GET https://safe-client.staging.gnosisdev.com/v1/chains`

**Comment by katspaugh** [comment]
It works, thank you!

Can we make Features editable from the Chain entry (as opposed to editing chains in each Feature)?

**Comment by fmrsabino** [comment]
> Can we make Features editable from the Chain entry (as opposed to editing chains in each Feature)?

Will check on the requirements for this 👍
