### ISSUE TITLE
Map rejected transactions as "REJECTED"

### ISSUE THREAD

**Issue by iamacook** [gnosis/safe-client-gateway#696]
**Is your feature request related to a problem? Please describe.**
Rejected transactions remain `"AWAITING_EXECUTION"` and it is not possible to determine whether it is indeed rejected or not.

**Describe the solution you'd like**
When a transaction is/was rejected, the status should be set to `"REJECED"`.

**Comment by rmeissner** [comment]
Documented Safe state definition: https://github.com/gnosis/safe/wiki/Safe-transaction-states

**Comment by jpalvarezl** [comment]
Hi, just a question about the spec. 

I have opened a draft PR #719 where you can find the logic for calculating the new status. Just to provide a summary:

- `EthereumTransactions`
  - Always `TransactionStatus::Success`
- `ModuleTransactions`
  - Either `TransactionStatus::Success` or `TransactionStatus::Failure`
- `MultisigTransaction`
```rust
        if self.is_executed {
            if self.is_successful.unwrap_or(false) {
                TransactionStatus::Success
            } else {
                TransactionStatus::Failed
            }
        } else if safe_info.nonce > self.nonce {
            TransactionStatus::Cancelled
        } else if rejection_count > 0 {
            TransactionStatus::Rejected
        } else if self.confirmation_count() < self.confirmation_required(safe_info.threshold) {
            TransactionStatus::AwaitingConfirmations
        } else {
            TransactionStatus::AwaitingExecution
        }
``` 

This euristic still has the problem that a `Cancellation` transaction it self gets flaged as `Rejected`. So I realise that I need to work on that, but my question is the following:

Am I understanding correctly, that a `Rejected` transaction is one such that it is either `AwaitingConfirmation` or `AwaitingExecution` with a proposed cancellation transaction (same nonce + parameters set to `0`) that is not necessarily executed yet?

**Comment by iamacook** [comment]
> Am I understanding correctly, that a Rejected transaction is one such that it is either AwaitingConfirmation or AwaitingExecution with a proposed cancellation transaction (same nonce + parameters set to 0) that is not necessarily executed yet?

This works well for us.

**Comment by jpalvarezl** [comment]
Just in addition to the previous comments and for the sake of documenting this in the issue too: this change would represent an API breaking change for the mobile clients, as discussed [here](https://gnosisinc.slack.com/archives/CQB729LLF/p1638203245429500)

**Comment by rmeissner** [comment]
I would not differentiate between rejected and cancelled. I would summarise both as "replaced"

**Comment by rmeissner** [comment]
Looking at the PR, we already have the status "cancelled", why do we require the rejected status?

**Comment by mikheevm** [comment]
I agree with @rmeissner regarding the "replaced" status. I can see on Discord that many people are struggling to understand how rejections work, and the problem there could be that we present them as rejections while they're replacements under the hood. Maybe our new designers can have a fresh take on this.

**Comment by jpalvarezl** [comment]
We have opted for now to simply use the `rejectors` list to infer whether a `replacement` transaction was proposed.
