### ISSUE TITLE
Expose contract endpoints through the gateway

### ISSUE THREAD

**Issue by yagopv** [gnosis/safe-client-gateway#700]
**Is your feature request related to a problem? Please describe.**

The [Transaction Builder app](https://github.com/gnosis/safe-react-apps/tree/development/apps/tx-builder) allow users to use operations in smart contract. For that we need to get the abi first. 

Currently we are not using any api key for etherscan or similar apis and we are having problems reaching API rate limits (https://github.com/gnosis/safe-react-apps/issues/169). We can get an API key in etherscan and we are ready to go but as getting contract information as the abi can be typical use case we would like to have the option through the gateway.

**Describe the solution you'd like**

We would like to have the contract endpoints exposed, particularly the `/contract/{address}` one:

![image](https://user-images.githubusercontent.com/1576776/143053942-12246aa9-a65c-4dd7-aefd-3adb839ef45f.png)

Besides this, as not all the contracts will be exposed, a fallback mechanism would be really appreciated. For example, going to etherscan or the corresponding api (depending on the network) or using something like [Sourcify](https://sourcify.dev).
This way we can keep as well the api keys centralized in the transaction service instead reinventing solutions across the apps/sdks

**Describe alternatives you've considered**

We were thinking about making direct calls against the endpoint or even using sourcify instead our services.

**Additional context**

Currently we have support for these networks through the different apis:

https://github.com/gnosis/safe-react-apps/blob/4c845075674bb7732a4702ede3c56297d7b56fcb/apps/tx-builder/src/hooks/useServices/interfaceRepository.ts#L18-L37

**Comment by jpalvarezl** [comment]
Hi @yagopv we discussed the spec during our backend sync meeting. 
- We would implement the endpoint `/v1/chains/<chain_id>/contracts/<contract_address>`
- We want to avoid implementing any fallback logic in the services
- We would recommend using `sourcify` first and use our services as a client. As it supports dev documentation that our services do not provide.

**Comment by yagopv** [comment]
For me is ok.

I never used that but guess `sourcify` is intented to be used with direct REST calls to `https://sourcify.dev/server` right @dasanra ?

For example:

```
curl 'https://sourcify.dev/server/checkByAddresses?addresses=0x6b175474e89094c44da98b954eedeac495271d0f&chainIds=1,3,4,42,5,100,77,56,97,137,80001,42220,44787,62320,43113,43114,42161,421611,40,41,8,4216137055,5700,10,69,288,28' \
  --compressed
```

And if not found we would use the new endpoint in the gateway. 

nice to me :)
