### ISSUE TITLE
Investigate traffic volume in legacy instances of the CGW

### ISSUE THREAD

**Issue by jpalvarezl** [gnosis/safe-client-gateway#706]
## Feature

We would like to shut down our legacy instances of the `CGW`

## Context

In order to be able to do this we need to determine if traffic is still directed to them. Document the volume of traffic using kibana and then present it to the team to make a decision.

## Usage report
https://docs.google.com/document/d/1Efp-Nd2PQntJdx2jlAHX74X1006H97rXwIm3m4kKzuw/edit?usp=sharing

**Comment by rmeissner** [comment]
we are planning on taking down the legacy environments for [rinkeby](https://safe-client.rinkeby.gnosis.io/about), [polygon](https://safe-client.polygon.gnosis.io/about) and [BSC](https://safe-client.bsc.gnosis.io/about) of the CGW .

- Rinkeby will be taken down by **February, 14th**.
- Polygon and BSC will be taken down by the **end of February**

We won’t be taking down [mainnet](http://safe-client.mainnet.gnosis.io/about) yet, we would do so once the desktop app migrates to use the unified CGW.
