### ISSUE TITLE
Return current safe contract nonce as part of the estimation

### ISSUE THREAD

**Issue by sche** [gnosis/safe-client-gateway#711]
Currently, estimation returns `latest_nonce` and `safe_tx_gas` fields (https://gnosis.github.io/safe-client-gateway/docs/routes/safes/models/struct.SafeTransactionEstimation.html)

It would be helpful to get the contract `nonce` field as part of the estimation. It can improve UX when editing transaction parameters. We can display an explicit error if a user tries to specify a nonce that is already used.

Related EPIC: https://github.com/gnosis/safe/issues/503

**Comment by jpalvarezl** [comment]
I would need to know what you mean by "contract nonce" . Is that the current nonce of the safe? As in the `nonce` field in the response from this endpoint: https://safe-client.staging.gnosisdev.com/v1/chains/4/safes/0x1230B3d59858296A31053C1b8562Ecf89A2f888b/ ?

**Comment by sche** [comment]
@jpalvarezl 
> As in the nonce field in the response from this endpoint

Yes, from this endpoint. Thank you!

**Comment by jpalvarezl** [comment]
We will add this field under the name of `current_nonce` as part of the response of the estimation endpoint.
