### ISSUE TITLE
`trusted` flag for `DELEGATE_CALL` transactions

### ISSUE THREAD

**Issue by jpalvarezl** [gnosis/safe-client-gateway#725]
## Feature

Propage `trusted` flag for delegate calls to contracts returned by the core services (see [comment](https://github.com/gnosis/safe-client-gateway/issues/725#issuecomment-989806242) for full spec)

>  - `trustedDelegateCallTarget : Option<bool>` if it's a `CALL` tx we don't send it. If it's a `DELEGATE` it is either true or false, according to what is returned by the `contracts` endpoint from the core services.
> - Nested `DELEGATE` in `multiSend`: Always warn about them
> - The flag can be found `TransactionDetails::TransactionData::trustedDelegateCallTarget` (`TransactionData` is nullable, however it is never null for `Module` and `Multisig` Transactions)

**Comment by rmeissner** [comment]
See for example: https://safe-transaction.mainnet.gnosis.io/api/v1/contracts/0x40A2aCCbd92BCA938b02010E17A5b8929b49130D/

**Comment by rmeissner** [comment]
Option to evaluate:
- Add parameter to root of transaction details `trustedDelegateCallTarget`

To keep in mind:
- What is expected for "Call" transactions
- How do we handle nested multisends with delegatecall
  - Always warn 
- Make sure to cover also ModuleTransactions

**Comment by jpalvarezl** [comment]
`trustedDelegateCallTarget : Option<bool>` if it's a `CALL` tx we don't send it. If it's a `DELEGATE` it is either `true` or `false`

**Comment by iamacook** [comment]
This all sounds good. When said flag is implemented, we can make the relevant adjustments on our side.

**Comment by jpalvarezl** [comment]
Add check for nested multi_send
