### ISSUE TITLE
Provide name and logo for the transaction details txData.to field

### ISSUE THREAD

**Issue by DmitryBespalov** [gnosis/safe-client-gateway#732]
When showing advanced transaction details, we'd like to show the `txData.to` with the known address name and logo, if it's available.

Currently it only returns the address value.

[Example Response](https://safe-client.gnosis.io/v1/chains/1/transactions/multisig_0x84443F61efc60D10DA9F9a2398980CD5748394BB_0x0f234d2881036da130be836d4a1721a2f9846d6589ace5bbcb1ed7cbadd7c1fc)

[Current implementation](https://github.com/gnosis/safe-client-gateway/blob/main/src/routes/transactions/converters/details.rs#L31)

Linked issue: https://github.com/gnosis/safe-ios/issues/1571

**Comment by DmitryBespalov** [comment]
@jpalvarezl if that's ok, then please go ahead :-) we show the txData.to in a separate screen and it's more convenient to have all the info available there, too.

**Comment by jpalvarezl** [comment]
Yeah, no problem :) If this is shown independently it makes total sense 🙌
