### ISSUE TITLE
Extra 'standardised' chain name field

### ISSUE THREAD

**Issue by iamacook** [gnosis/safe-client-gateway#747]
**Is your feature request related to a problem? Please describe.**

[Onboard](https://docs.blocknative.com/onboard), used in frontend for wallet interaction, has an [archived dependency](https://github.com/ethereumjs/ethereumjs-common) with [hardcoded](https://github.com/ethereumjs/ethereumjs-common/blob/a978f630858f6843176bb20b277569785914e899/src/index.ts#L61) [chain names](https://github.com/ethereumjs/ethereumjs-common/blob/a978f630858f6843176bb20b277569785914e899/src/chains/index.ts#L4): `'mainnet'`, `'ropsten'`, `'rinkeby'`, `'kovan'` and `'goerli'`. This has the knock-on effect that Onboard's [`networkName` init option](https://docs.blocknative.com/onboard#networkname-optional) must match one of these names when the corresponding chain is being interacted with.

`chainName.toLowerCase()`, from the chains endpoint, is currently being used as the `networkName` (and also for the `localStorage` key) in frontend. With the change from `'Mainnet'` to `'Ethereum'`, this originally broke the Onboard integration of `'mainnet'` support from the above list. As a quickfix, we hardcoded `'mainnet'` back in.

If we were to change a `chainName` in the future and it not correspond to the hardcoded names, it would break the Onboard integration again.

**Describe the solution you'd like**

The addition of a 'standardised' chain name field that we can reference in the Onboard configuration. It would be best to match the [ethereum-lists/chains format](https://github.com/ethereum-lists/chains/blob/master/_data/chains/eip155-1.json#L4) as closely as possible.

Suggested added field names are as follows:
- `onboardName`
- `network`
- `uniqueNetworkSlug`

Breaking change field names:
- `chainName` => `displayName`, adding `name`/`network`

**Describe alternatives you've considered**

A local lookup for the hardcoded network names. This, however, goes against the desired mantra of remaining as agnostic as possible.

**Comment by rmeissner** [comment]
Decision:
- Add `chainNetwork` that should correspond to the `network` field from https://github.com/ethereum-lists

**Comment by mikheevm** [comment]
@iamacook, did you ask onboard.js if they're looking to change that?

**Comment by iamacook** [comment]
@mikheevm, it looks as they are moving towards accepting [custom chain configuration](https://github.com/blocknative/onboard/blob/feature/v2/packages/core/README.md#initialization-example) in their next big version. If that's the case, we'd no longer require this in frontend.

I'll get in touch with them to confirm.

**Comment by fmrsabino** [comment]
> Decision:
> 
> * Add `chainNetwork` that should correspond to the `network` field from https://github.com/ethereum-lists

@rmeissner It seems that the field was deprecated https://github.com/ethereum-lists/chains/commit/62ad98d60e7fba1ce66514bbb52c430b032eaf33

**Comment by iamacook** [comment]
Blocknative got back to me with the following:

> Regarding the network name, that is defined for each network within the configuration and Onboard no longer keeps an internal map of networks. So that should solve the issue you are having!

We could remain with our current implementation and when onboard v2 is released, migrate to that and remove our hotfix logic/enable hardware wallets on the networks that aren't in the currently hardcoded list.

**Comment by fmrsabino** [comment]
> Blocknative got back to me with the following:
> 
> > Regarding the network name, that is defined for each network within the configuration and Onboard no longer keeps an internal map of networks. So that should solve the issue you are having!
> 
> We could remain with our current implementation and when onboard v2 is released, migrate to that and remove our hotfix logic/enable hardware wallets on the networks that aren't in the currently hardcoded list.

Which list/map will be used to validate the network name then?

**Comment by iamacook** [comment]
> Which list/map will be used to validate the network name then?

The next version doesn't require a network name but [just a label](https://github.com/blocknative/onboard/tree/feature/v2/packages/core#initialization-example) but you make a valid point. We rely on the network name to save configuration data locally. Please disregard my previous comment.

**Comment by fmrsabino** [comment]
> The next version doesn't require a network name but [just a label](https://github.com/blocknative/onboard/tree/feature/v2/packages/core#initialization-example) but you make a valid point. We rely on the network name to save configuration data locally. Please disregard my previous comment.

I wonder if the `label` that it is mentioned refers to the `name` field under https://github.com/ethereum-lists/chains/blob/master/_data/chains/eip155-1.json 🤔

**Comment by fmrsabino** [comment]
@gnosis/safe-web If `onboard.js` just requires a `chainId` and the `label` is optional (can be used for UI purposed) then I'd close the issue as this is already provided by the Safe Client Gateway. What do you think?

**Comment by mikheevm** [comment]
@iamacook I may miss something but the last time I fixed the issue it wasn't onboard.js but ledger/trezor libraries that required a certain name to work

**Comment by iamacook** [comment]
This is related to the current version of onboard as the network name is passed onto wallets. We are currently [hardcoding 'mainnet'](https://github.com/gnosis/safe-react/blob/c3baa546cd04329024866708b3479f42554e60e8/src/logic/wallets/onboard.ts#L24) as it's currently 'Ethereum' on the CGW.

We also use network names in our `localStorage` keys to save information. However, it would definitely make more sense to use the network id there. We would first have to migrate everything though. @katspaugh, what do you think?

**Comment by katspaugh** [comment]
For LS keys, the numeric chainId totally makes sense, yes.

**Comment by katspaugh** [comment]
I still think having an id-like, but human-readable, chain name is useful going forward. As per Richard's comment above:

> Add chainNetwork that should correspond to the network field from https://github.com/ethereum-lists

**Comment by iamacook** [comment]
> For LS keys, the numeric chainId totally makes sense, yes.

I have created an issue https://github.com/gnosis/safe-react/issues/3300 for the migration to use network ids instead.

**Comment by fmrsabino** [comment]
I would say that the chain id should be used whenever possible. It doesn't need to be human readable. To have a human readable form we already have a name for that chain (which can change – eg.: `xDai` to `Gnosis Chain`).

Having a unique field tied to another unique field for the same object can raise more validation questions. `100 : xDAI` vs `100 : Gnosis Chain`.

> I still think having an id-like, but human-readable, chain name is useful going forward. As per Richard's comment above:
> 
> > Add chainNetwork that should correspond to the network field from https://github.com/ethereum-lists

This fields was deprecated: https://github.com/gnosis/safe-client-gateway/issues/747#issuecomment-1011055188

**Comment by fmrsabino** [comment]
@gnosis/safe-web any update on this issue?

**Comment by katspaugh** [comment]
Update as in, whether you can close it? No, we still need it.

**Comment by fmrsabino** [comment]
> Update as in, whether you can close it? No, we still need it.

So what is the current status? Does `onboard.js` work with chain ids at the moment?

**Comment by iamacook** [comment]
`Onboard` works, but the issue still remains with `mainnet` being hardcoded somewhere. We have also hardcoded a workaround for it though. Their upcoming version could fix this, but that is just an assumption as @mikheevm said it could even be HW wallet related. There is also no earmarked release date for it either.

Safe Apps have also encountered an issue with the renaming of `xDai` to `Gnosis Chain` that would likely benefit from this too. cc @dasanra

**Comment by fmrsabino** [comment]
> Their upcoming version could fix this, but that is just an assumption as @mikheevm said it could even be HW wallet related. There is also no earmarked release date for it either.

Ok so we don't know at the moment if this is an Hardware Wallet issue or, if it is, if there's an upcoming version of `onboard.js` to fix this.

Thanks for clarifying.

To reiterate on the following: **the network field was removed from the ethereum list repo.**

We already have a unique numeric field to identify the chain and we also have a display name that is not unique to be displayed no the interfaces.

I'd see value in adding a new unique field **IFF** there's no way around integration with required 3rd parties (ie.: a requirement of a non-standard unique field that identifies a chain besides its id).

**Comment by iamacook** [comment]
We are currently coping with the issues we encountered, albeit with questionable code.

We do use the names for our `localStorage` keys but we intend to migrate those to using the `chainId` at some point. I currently cannot see any benefit in adding a new field for the time being.

**Comment by mikheevm** [comment]
> Safe Apps have also encountered an issue with the renaming of xDai to Gnosis Chain that would likely benefit from this too. cc @dasanra

Safe Apps problem isn't related. We used to pass the chain name along with the Safe info but removed it in later versions. With the rename, the apps that relied on old names stopped working

**Comment by iamacook** [comment]
I guess we can close this then. Wdyt @katspaugh?

**Comment by katspaugh** [comment]
Closing, thanks for the details 👍
