### ISSUE TITLE
Inconsistent logic in propose endpoint

### ISSUE THREAD

**Issue by rmeissner** [gnosis/safe-client-gateway#757]
**Describe the bug**
The propose endpoint uses an inconsistent logic to determine `latestNonce`. 

If there are transactions with a nonce higher or equal to the current Safe nonce, it returns this nonce, which then indicates to the clients that they should use `latestNonce + 1` for the next transaction. But if there is no such transaction the endpoint returns the current Safe nonce, therefore the `+ 1` would skip one nonce that should be used. Another issue is that it defaults to `0` in case that no known tx is available.

**Expected behavior**
A nonce should be returned that can be immediately used without further adjustments.

**Additional context**
Fallback to current nonce was introduced with #754

**Proposed solution**
- Revert #754 
- Add v2 estimate endpoint with  `recommendedNonce` field instead of `latestNonce` that returns the nonce that should be used for the next transaction

**Comment by mikheevm** [comment]
What would it return if there are transactions with a gap in nonces? Let's say there are queued transactions with nonces 2 and 10

**Comment by rmeissner** [comment]
11 would be returned for now. If we want to improve/change this I would do this as a separate improvement issue.

**Comment by MouazAlzahabi** [comment]
So if there is no tx, will recommendedNonce be 0 ?
