### ISSUE TITLE
Transactions list: The transaction status is changed with a big delay

### ISSUE THREAD

**Issue by liliya-soroka** [gnosis/safe-client-gateway#76]
**Describe the bug**
Status of the transaction is changed with the delay of more than 10 min from awaiting execution to execute.
The same was with changing statuses from awaiting confirmation to awaiting execution - the status was updated when the new transaction was created

**To Reproduce**
1. Create a transaction in the safe with a few confirmation
2. Open mobile app
3. Check transactions list
Current result: The transaction in the Queue appears

4. Confirm transaction without executing 
5. Wait til the status is updated in the web app
6. Refresh the page ( pull to refresh, switch safes, go to another page and come back, restart the app)
Current result: The transaction status is not changed for a long time.

**Expected behavior**
The status on the client should be changed as soon as it's changed on the back-end

**Desktop (please complete the following information):**
 - OS: android
 - Version 0.2.0

**Additional context**

**Comment by rmeissner** [comment]
This is expected as cache invalidation is not enabled for the heroku deployment
