### ISSUE TITLE
Tx estimation returns wrong nonce

### ISSUE THREAD

**Issue by sche** [gnosis/safe-client-gateway#768]
**Support issue**
https://discord.com/channels/907968493134155807/913377923308871680/926106597875400814

**Describe the bug**
Safe: https://gnosis-safe.io/app/eth:0xc5b3F8D30429ad048fA01d479fB1a7BFe651d04D/transactions/queue
A user has many transactions in a queue. When the nonce reached 100, our UI always suggested nonce 100 for all new transactions.

![image](https://user-images.githubusercontent.com/2284385/147910314-b1d7752e-3e33-4610-b2a4-b02084d1392e.png)

**Comment by sche** [comment]
**Update**: The user claimed that when he tried to do a new transaction the correct nonce is set automatically and confirmed that the issue is already resolved.

Probably not an issue anymore. Would be still good to understand the root cause of proposing the same nonce in an estimation.

**Comment by rmeissner** [comment]
Is this really service related or is this react related?

If you use `safe-client.gnosis.io/v2/chains/1/safes/0xc5b3F8D30429ad048fA01d479fB1a7BFe651d04D/multisig-transactions/estimations` with a post of a cancelation tx you get nonce `106`

**Comment by sche** [comment]
The issue is not there anymore. Why it was there on 31.12.2021 is unclear. Could we make a fast checkup in logs for this safe? If the service was responding with nonce=101, this is most likely a react issue.
