### ISSUE TITLE
setGuard and deleteGuard display as settings transactions

### ISSUE THREAD

**Issue by DiogoSoaress** [gnosis/safe-client-gateway#813]
## Description
For the **setGuard** and **deleteGuard** transaction types, both should be displayed as Settings transactions. Similarly to **changeMastercopy** transactions

## Environment
 - Browser: Chrome
 - Wallet: MetaMask
 - Chain: Rinkeby

## Steps to reproduce
 1. Open rin:0x6cf158C37354d8da5396fb6d3e965318CCf119c1 safe and observe that the **setGuard** transaction

## Expected result
**setGuard** and **deleteGuard** transaction should display as Settings transactions

## Screenshots
![image (4)](https://user-images.githubusercontent.com/32431609/154719294-415e4c23-1df0-4eec-be6b-592509b53613.png)

**Comment by rmeissner** [comment]
@gnosis/safe-web @gnosis/safe-ios what happens if we add a new type to the SettingChange on the clients?

**Comment by rmeissner** [comment]
There would be a new version of the `settingsInfo` (see https://github.com/gnosis/safe-client-gateway/blob/main/src/routes/transactions/models/mod.rs#L129-L149)

**Comment by iamacook** [comment]
I think we should be fine on the frontend. Would just need to update our types.

**Comment by DmitryBespalov** [comment]
if CGW starts returning these types, the iOS client will display the transactions as "Unknown" settings change
