### ISSUE TITLE
Refactor Multisig Transaction classification logic

### ISSUE THREAD

**Issue by jpalvarezl** [gnosis/safe-client-gateway#92]
**Is your feature request related to a problem? Please describe.**
Multisig Transaction classification is a bit confusing and could be refactored. Specifically, there is a `token_info` request on every classification, which doesn't make sense in 60% of the cases (in the unit tests we just mock it as an error reponse). These cases are `Transfer::Ether`, `SettingsChange` and `Custom` transaction.

**Describe the solution you'd like**
The solution should prevent unnecessary requests to the `InfoProvider` even though we have a cache, we are not able to distinguish an error that matters from an error that happens when the request doesn't make sense given the context.

**Describe alternatives you've considered**
Switching the order of checks so that we only request token information when we strictly need it. However, the order in which we check could matter. First, we should cover with unit tests before commencing this refactor.

**Comment by rmeissner** [comment]
I would rewrite the classification logic completely. Currently it checks multiple times the data decoded for the same information and delaying the loading of token information would require some code duplication.

As mentioned in the description of the issue I would also try to identify specific transactions that don't require external information first:

```
// Quick exit for custom ... do we want this?
if (value > 0 and len(data) > 0) or operation != 0:
  return parse_custom_tx(tx)

//  operation == 0 is implied by check above
if value > 0 and len(data) == 0: // len(data) == 0 could be left out as it implied by check above after value check
  return parse_ether_transfer(tx)

//  operation == 0 is implied by check above
if value == 0 and len(data) > 0 and to == safe: // value == 0 could be left out as it implied by check above after data len check
  return parse_settings(tx)

if data.is_transfer_method():
  if data.requires_participant_check() and !data.check_participants():
    return parse_custom_tx(tx)
  let token = load_token_info(to)
  if no token:
    return parse_custom_tx(tx)
 return parse_token_transfer(tx, token) // Token type will define what kind of token transfer it is

return parse_custom_tx(tx)
```

**Comment by jpalvarezl** [comment]
>  if data.requires_participant_check() and !data.check_participants()

@rmeissner Not sure what this check is about. What did you mean by those methods?

**Comment by rmeissner** [comment]
For some transfer types we need to check if to or from are the safe
