### ISSUE TITLE
Can't use the "next" or "previous" urls in the iOS app

### ISSUE THREAD

**Issue by DmitryBespalov** [gnosis/safe-client-gateway#97]
Unfortunately, iOS doesn't properly processes the currently  used URLs for  the `next` and `previous` links in the transaction summary list response.

The  issue is that those URLs contain percent-encoded query parameters (key=value) and that is used  as a value for  the `next` query parameter.

Base URL:
https://safe-client-rinkeby.staging.gnosisdev.com/v1/safes/0x5d2F66B7b591198cA36450EFB56823EE26967144/transactions

Next URL:
https://safe-client-rinkeby.staging.gnosisdev.com/v1/safes/0x5d2F66B7b591198cA36450EFB56823EE26967144/transactions?next=limit%3D20%26offset%3D20

What happens is  that  the percent symbols get themselves percent encoded  on the iOS side.

If  I remove the percent encoding from the URL, the URL becomes
https://safe-client-rinkeby.staging.gnosisdev.com/v1/safes/0x5d2F66B7b591198cA36450EFB56823EE26967144/transactions?next=limit=20&offset=20

Which doesn't work - the gateway ignores the limit and offset parameters.

I have noticed that the  "next=" parameter is used  for  both next and previous links. Maybe  it  can be removed completely? In  that  case, we can use simple URLs like

https://safe-client-rinkeby.staging.gnosisdev.com/v1/safes/0x5d2F66B7b591198cA36450EFB56823EE26967144/transactions?limit=20&offset=20

That would solve  the issue.

Of course, another way would be to use some sort of item identifier or anchor - example of it would be  a Twitter API  that also deals with the pagination.

**Comment by rmeissner** [comment]
Why do you need to perform url encoding here? Can't you use the url as is and use it to perform a request?

**Comment by DmitryBespalov** [comment]
Was  trying to do that but  so far couldn't integrate it well in services layer. Will try again

**Comment by rmeissner** [comment]
In general you should not decode the `next` field. It should be treated as a url that should be directly used. If you decode it, normal URL decoders should decode the next param correctly (as a query param). The encoding used is a global standard for URL and it should be possible to use common functions (e.g. https://developer.apple.com/documentation/foundation/nsstring/1409569-removingpercentencoding).

**Comment by DmitryBespalov** [comment]
Ok, so we just use the URL as is. Then, should we check the base url (host) that it doesn't change to another host in order to restrict this url forwarding for security sake?

**Comment by DmitryBespalov** [comment]
I'm closing this issue as I found how to fix this. Thank you @rmeissner
