### ISSUE TITLE
Transaction Details:  500 for invalid transaction ID instead of 404

### ISSUE THREAD

**Issue by DmitryBespalov** [gnosis/safe-client-gateway#98]
**Describe the bug**
The  server returns 500 error when requesting transaction details with transaction ID that does not exist or is an invalid hash

**To Reproduce**
Invalid hash:
- https://safe-client-rinkeby.staging.gnosisdev.com/v1/transactions/0x0000000000000000000042c3aa02993a2f6906662671a72e646dc28c8935422a

Invalid id:
- https://safe-client-rinkeby.staging.gnosisdev.com/v1/transactions/123
- https://safe-client-rinkeby.staging.gnosisdev.com/v1/transactions/multisig_123

**Expected behavior**
Server returns  404 not found

**Desktop (please complete the following information):**
 - OS: Desktop
 - Browser: Firefox

**Comment by rmeissner** [comment]
This is related to https://github.com/gnosis/safe-client-gateway/issues/54 and will be handled with that. 

Nore: Currently everything is a 500
