### ISSUE TITLE
Transaction Summary List: invalid offset results in some data

### ISSUE THREAD

**Issue by DmitryBespalov** [gnosis/safe-client-gateway#99]
**Describe the bug**
When using very high  offsets, the result contains just the creation transaction

**To Reproduce**
Offset  20000:
- https://safe-client-rinkeby.staging.gnosisdev.com/v1/safes/0x5d2F66B7b591198cA36450EFB56823EE26967144/transactions?next=limit%3D2000%26offset%3D20000

**Expected behavior**
This behavior is undefined.
I think, last page of the transactions list should be returned (offset should  be capped at maximum)

**Comment by jpalvarezl** [comment]
For now this is the expected behaviour.`offset` and `limit` are query parameters that belong to the transaction service so technically it is possible to inject behaviour through them, but eventually we will try to encode the string and make the value more opaque to the users of the API.
